table Budget
	lineageTag: 508d83b3-5d75-40a0-90ba-6447c34bd6ea

	column CountryRegion
		dataType: string
		lineageTag: 6636113a-63c0-4ba8-98e9-c752d557c419
		summarizeBy: none
		sourceColumn: CountryRegion

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: bfa8194e-ce80-4702-a286-5d57478d6ae1
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: ea62f9be-05da-4182-a746-9f1774be605f
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: int64
		formatString: #,0.00
		lineageTag: 8fb90439-e71d-4d36-b78e-d575f48cbe4c
		summarizeBy: sum
		sourceColumn: Budget

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Budget-5dfd0575-fa9e-44b9-b0e1-25144c703ca4 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("H:\SQLBI\Conferences\User Group Sessions\Budgeting with Power BI\Budget.xlsx"), null, true),
				    Budget_Table = Source{[Item="Budget",Kind="Table"]}[Data],
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Budget_Table, {"CountryRegion", "Brand"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Scenario"}, {"Value", "Budget"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"CountryRegion", type text}, {"Brand", type text}, {"Budget", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Scenario Sort", each if [Scenario] = "Low" then 1 else if [Scenario] = "Medium" then 2 else 3),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Scenario Sort"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

