{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Remove_Live_azure\",\"Live_azure_TopLevel\",\"KFR_ET_TravelPattern\",\"KFR_ET_Report\",\"RegionCompTable\",\"CurrencyTable\",\"KFR_ET_DIM_Slicer2\",\"KFR_ET_DIM_Slicer1\",\"KFR_ET_TravelPattern_Unmatched\",\"KFR_ET_TravelPattern_Unmapped\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "c0e99943-f78b-441c-992d-4ec7e9f460b4",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "BudgetSeasonNum",
        "toTable": "Dim_BudgetSeasonNum"
      },
      {
        "name": "75fdf5a3-9588-445d-8cb5-882099818e98",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "BusinessUnit",
        "toTable": "Dim_BusinessUnit"
      },
      {
        "name": "620fddde-d962-4920-a005-019a9d7cff4c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "CompTypeCode",
        "toTable": "Dim_CompTypeCode"
      },
      {
        "name": "e532166c-2a4a-48ed-bcd6-b74d68731848",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "ProductMarketCode",
        "toTable": "Dim_ProductMarketCode"
      },
      {
        "name": "ce852ded-c69d-4323-b687-1da3b47d0cf3",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "StartLocationCountryName",
        "toTable": "Dim_StartCountry"
      },
      {
        "name": "2b93ad4a-0adf-4549-aeee-e7465c77c906",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "TourCode",
        "toTable": "Dim_TourCode"
      },
      {
        "name": "2c98aa54-9688-4811-94ad-4db3deea41eb",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "TourTypeCode",
        "toTable": "Dim_TourTypeCode"
      },
      {
        "name": "2f7ef4cf-f45e-40cd-9a0d-58c4e0f396a1",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "TourRegionCode",
        "toTable": "Dim_TourRegionCode"
      },
      {
        "name": "9023612f-5fd8-4873-bb28-e82fe10f86fe",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "LookupCode",
        "toTable": "Dim_LookupCode"
      },
      {
        "name": "c70c6ad4-45a4-4bbd-b664-2bc1a0f3f40a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductMarketCode",
        "fromTable": "Dim_MultipleAxis",
        "isActive": false,
        "toColumn": "CurrencyCode",
        "toTable": "Dim_CurrencyCode"
      },
      {
        "name": "000191c8-2e4e-4195-bad8-c1e0aad0c080",
        "fromColumn": "KFR_DATE",
        "fromTable": "KFR_ET_TravelPattern",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4b9ff6d5-2466-4975-9d40-5891325a8acb"
      },
      {
        "name": "712cd2f1-658a-46cd-8c65-a2ebcab04596",
        "fromColumn": "DEPARTUREDATE",
        "fromTable": "KFR_ET_Report",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_af4f99d0-a7e4-4bf4-a3ca-4429e1d7f0c2"
      },
      {
        "name": "dd644ebb-c5d1-46af-bf1d-773b8cccbfd9",
        "fromColumn": "Date",
        "fromTable": "KFR_ET_Report",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2060e6c-ad33-450c-aaf3-64a78030d959"
      },
      {
        "name": "a6ac73da-a6b8-4628-a50e-7464ec54b39f",
        "fromColumn": "Date",
        "fromTable": "KFR_ET_DIM_Slicer2",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ba2a9a6e-81ba-4409-8de6-2dcda6adf988"
      },
      {
        "name": "14b5c9bb-dc73-4921-80b2-e9a7a132286c",
        "fromColumn": "Date",
        "fromTable": "KFR_ET_DIM_Slicer1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_86061e0a-7362-49b8-bd90-4e103c4ea353"
      },
      {
        "name": "0ebff29c-c0f9-4c66-99ef-d52c2f12f269",
        "fromColumn": "KFR_DATE",
        "fromTable": "KFR_ET_TravelPattern_Unmatched",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b3ab996e-41d5-4c37-bbe6-9d01d770e1cd"
      },
      {
        "name": "60cc361e-df77-47ee-9a91-1526ea173cf5",
        "fromColumn": "DEPARTUREDATE",
        "fromTable": "KFR_ET_TravelPattern_Unmatched",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b54472eb-b572-4a2f-b7fc-28bc7c405a12"
      },
      {
        "name": "37608bb4-ed89-4bf1-8945-b00578c3c172",
        "fromColumn": "TP_KEY_EXT_UNIQUE",
        "fromTable": "KFR_ET_Report",
        "toColumn": "TP_KEY_EXT_UNIQUE",
        "toTable": "KFR_ET_TravelPattern"
      },
      {
        "name": "fbb96db8-6217-4383-9583-596f9365aba7",
        "fromColumn": "CurrencyCode",
        "fromTable": "KFR_ET_Report",
        "toColumn": "CURRENCYCODE",
        "toTable": "CurrencyTable"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Remove_Live_azure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "92a313fc-14f5-40e9-9164-404d7599022b",
            "sourceColumn": "ID",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "RegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d37681fd-c754-4e67-b9ee-2f29b3d46219",
            "sourceColumn": "RegionCode",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "RegionCode_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7793f572-9b85-47e3-b9b6-9c618dc1bcbe",
            "sourceColumn": "RegionCode_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c43d9b2-5e7f-4c23-82b1-a47e8447d688",
            "sourceColumn": "TourCode",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "TourCode_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7cbddba0-8c25-4989-9d11-2c711e2c9adc",
            "sourceColumn": "TourCode_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "TourVersion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49be0666-095a-4adf-ab91-287eeda9c18b",
            "sourceColumn": "TourVersion",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "TourVersion_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "70ce7e9a-aa68-411c-b022-9e65d4e3cf1a",
            "sourceColumn": "TourVersion_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetSeason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b032dc83-c9f3-4358-9ed6-b2038cbda39b",
            "sourceColumn": "BudgetSeason",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetSeason_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5b7d75b-055d-4754-a604-1ed5b8573228",
            "sourceColumn": "BudgetSeason_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "CompTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83b1e9ad-f98a-48ae-bff4-562d94cbaf68",
            "sourceColumn": "CompTypeCode",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CompTypeCode_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2656bed-ad20-42c9-b024-189a0485183c",
            "sourceColumn": "CompTypeCode_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "LookupCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d895c2c-c753-4892-a45f-5f14bf200db9",
            "sourceColumn": "LookupCode",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "LookupCode_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "84aea3e5-939c-4d2d-9db6-ddfec44bc80a",
            "sourceColumn": "LookupCode_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5be9f88-778b-49ee-a8a8-9c3070d7a792",
            "sourceColumn": "CurrencyCode",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyCode_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "523dab67-b467-4001-8387-f3f2ef21dcd4",
            "sourceColumn": "CurrencyCode_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "TimeStamp_GMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isNullable": false,
            "lineageTag": "2e722eb1-48cd-48d1-a115-eaf47c63c51a",
            "sourceColumn": "TimeStamp_GMT",
            "sourceProviderType": "datetime",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a310ca8-f60c-449e-9346-7be9ffe6e4fa",
        "partitions": [
          {
            "name": "Remove_Live_azure-f1cf2dbc-6543-4678-b05e-74250abf667f",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"tours-power-apps.database.windows.net\", \"TravelerAnalysis\", [Query=\"SELECT #(lf)*#(lf)FROM TravelerAnalysis.[dbo].[KFR_B2S_variables]\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "My_Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "141e1ffd6bbb4d48b4877e1c73ec4884"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "313d75c0-cc9d-4e66-9bf8-615c966bdf85",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "59a0005a-03a4-40bd-b959-62c0fda25d28",
        "measures": [
          {
            "name": "Curr_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "LOOKUPVALUE(Remove_Live_azure[CurrencyCode_shift], Remove_Live_azure[ID], MAX(Remove_Live_azure[ID]))",
            "lineageTag": "b895115e-5a46-493b-8669-b6c5f28202f3"
          },
          {
            "name": "Category_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "LOOKUPVALUE(Remove_Live_azure[CompTypeCode_shift], Remove_Live_azure[ID], MAX(Remove_Live_azure[ID]))",
            "lineageTag": "7c1ba03b-e5f7-4846-b557-c1a4f720f69e"
          },
          {
            "name": "Curr_sel",
            "expression": [
              "",
              "",
              "LOOKUPVALUE(Remove_Live_azure[CurrencyCode], Remove_Live_azure[ID], MAX(Remove_Live_azure[ID]))",
              "",
              "// Var MyId = MAX(Live_azure[ID])",
              "",
              "// // Var Calc = FILTER(Live_azure, Live_azure[ID] = max(Live_azure[ID]))",
              "",
              "// Return MyId "
            ],
            "lineageTag": "f50d5c5e-9a8e-4657-b4af-cb96ac3e4ce3"
          },
          {
            "name": "Sim_Pax_min_group_Curr",
            "expression": [
              "",
              "",
              "Var My_KFR = _measures[Slicer_KFR_1]",
              "Var My_ComponentPeriod = _measures[Slicer_Periods_1]",
              "Var My_FX = _measures[Slicer_FX_1]",
              "",
              "Var MyTourCode = SELECTEDVALUE(KFR_ET_Report[TourCode])",
              "Var MyVersion = SELECTEDVALUE(KFR_ET_Report[TourVersionCode])",
              "Var MySeason = SELECTEDVALUE(KFR_ET_Report[BudgetSeasonNum])",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(DISTINCT(KFR_ET_Report), KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "            && KFR_ET_Report[TourCode] = MyTourCode && KFR_ET_Report[TourVersionCode] = MyVersion && KFR_ET_Report[BudgetSeasonNum] = MySeason",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            , KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            // , KFR_ET_Report[LocalTotal_USD_group]",
              "    )",
              "    , \"NewUSD\", ",
              "        SWITCH(TRUE()",
              "            , KFR_ET_Report[CurrencyCode] = \"AUD\", DIVIDE(Z_AUD[AUD_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[CurrencyCode] = \"EUR\", DIVIDE(Z_EUR[EUR_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[CurrencyCode] = \"GBP\", DIVIDE(Z_GBP[GBP_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[CurrencyCode] = \"JPY\", DIVIDE(Z_JPY[JPY_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "        )",
              "   ",
              "    )",
              "",
              "Var USD_calc_group = ",
              "    DIVIDE(",
              "        SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD])",
              "        , [My_Travellers_1] //if travellers doesn't need to be amended.",
              "    ) ",
              " ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              " ",
              "Return Calc        "
            ],
            "lineageTag": "3479839a-5e66-408d-bec2-babd679cf3d7"
          },
          {
            "name": "Pax_1_sim",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "// Var MyCurr = [Curr_sel]",
              "// Var MyCurrRate = My_Measure[Curr_shift]",
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "            // && (KFR_ET_Report[CurrencyCode] = [Curr1] || KFR_ET_Report[CurrencyCode] = [Curr2] || KFR_ET_Report[CurrencyCode] = [Curr3] )",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                SWITCH(TRUE()",
              "",
              "                // , KFR_ET_Report[CurrencyCode] = [Curr1] //&& KFR_ET_Report[CurrencyCode] <> [Curr2] && KFR_ET_Report[CurrencyCode] <> [Curr3]",
              "                //     , SWITCH(",
              "                //             KFR_ET_Report[IsPerGroup] = FALSE()",
              "                //                 , KFR_ET_Report[LocalTotal_USD]",
              "                //                 , KFR_ET_Report[LocalTotal_USD_group]",
              "                //     )",
              " ",
              "                // Per Pax",
              "                , KFR_ET_Report[IsPerGroup] = FALSE()",
              "                    , SWITCH(TRUE()",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr1] ",
              "                            , (1 + Azure_measures[Curr1_shift]) * KFR_ET_Report[LocalTotal_USD]",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr2]",
              "                            , (1 + Azure_measures[Curr2_shift]) * KFR_ET_Report[LocalTotal_USD]",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr3] ",
              "                            , (1 + Azure_measures[Curr3_shift]) * KFR_ET_Report[LocalTotal_USD]",
              "                    )",
              "",
              "                // per Group",
              "                , KFR_ET_Report[IsPerGroup] = TRUE()",
              "                    , SWITCH(TRUE()",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr1] ",
              "                            , (1 + Azure_measures[Curr1_shift]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr2] ",
              "                            , (1 + Azure_measures[Curr2_shift]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                        , KFR_ET_Report[CurrencyCode] = [Curr3] ",
              "                            , (1 + Azure_measures[Curr3_shift]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                    )",
              "                )",
              "",
              "                    // //Currencies. --> preferably pre calculate the rate already. ",
              "                    // , KFR_ET_Report[IsPerGroup] = TRUE() && KFR_ET_Report[CurrencyCode] = [Curr1] && [Curr1] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr1_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                    // , KFR_ET_Report[IsPerGroup] = FALSE() && KFR_ET_Report[CurrencyCode] = [Curr1] && [Curr1] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr1_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "                    ",
              "                    // //Curr2",
              "                    // , KFR_ET_Report[IsPerGroup] = TRUE() && KFR_ET_Report[CurrencyCode] = [Curr2] && [Curr2] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr2_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                    // , KFR_ET_Report[IsPerGroup] = FALSE() && KFR_ET_Report[CurrencyCode] = [Curr2] && [Curr2] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr2_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "",
              "                    // //Curr3",
              "                    // , KFR_ET_Report[IsPerGroup] = TRUE() && KFR_ET_Report[CurrencyCode] = [Curr3] && [Curr3] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr3_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD_group]",
              "                    // , KFR_ET_Report[IsPerGroup] = FALSE() && KFR_ET_Report[CurrencyCode] = [Curr3] && [Curr3] <> BLANK()",
              "                    //     , DIVIDE([Rate]*(1+ [Curr3_shift]), KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "",
              "",
              "",
              "                    // , KFR_ET_Report[IsPerGroup] = TRUE()",
              "                    //     , KFR_ET_Report[LocalTotal_USD_group]",
              "                    // , KFR_ET_Report[IsPerGroup] = FALSE()",
              "                    //     , KFR_ET_Report[LocalTotal_USD]",
              "                ",
              "                // )",
              "",
              "                    // , KFR_ET_Report[CurrencyCode] = \"EUR\", DIVIDE(Z_EUR[EUR_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "                    // , KFR_ET_Report[CurrencyCode] = \"GBP\", DIVIDE(Z_GBP[GBP_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "                    // , KFR_ET_Report[CurrencyCode] = \"JPY\", DIVIDE(Z_JPY[JPY_sel], KFR_ET_Report[Rate]) * KFR_ET_Report[LocalTotal_USD]",
              "                    //, 0 //KFR_ET_Report[LocalTotal_USD]",
              "                // )",
              "",
              "    )",
              "",
              "// Var USD_calc_group = ",
              "//             DIVIDE(",
              "//                 SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [LocalTotal_USD]) * [My_BusCount_1]",
              "//                 , [My_Travellers_1]",
              "//             )",
              "",
              "Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc          "
            ],
            "formatString": "#,0",
            "lineageTag": "2a16192d-370c-42a5-ba2c-00039b77268a"
          },
          {
            "name": "Pax_1_sum_sim",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "Var MyYear = SELECTEDVALUE(KFR_ET_DIM_Slicer1[TP_year])",
              "",
              "// Var MyYear = VALUE(\"20\" & MID(SELECTEDVALUE(KFR_ET_DIM_Slicer1[Period]),2,2))",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [Pax_1_sim_Min] * [TP_Travellers_1]",
              "        )",
              "        , [TP_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "",
              "Var Calc2 = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [Pax_1] * [TP_Travellers_1]",
              "        )",
              "        , [TP_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "Var Calc3 = IF([Min_Group] = 0, Calc2, Calc)",
              "",
              "Return Calc3  "
            ],
            "lineageTag": "d8e4f3ee-ba63-4feb-9f25-00eaf432ab48"
          },
          {
            "name": "Pax_1_sim_v2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "    )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] && KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) * [TP_BusCount_1]",
              "                , [TP_Travellers_1]",
              "            )",
              "",
              "// Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc          "
            ],
            "lineageTag": "88e24c75-03a7-48c6-adf6-dd57f7c7dd5b"
          },
          {
            "name": "Pax_1_sim_v3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] && KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "    , \"NewUSD2\", ",
              "        if(KFR_ET_Report[Combination_Index] <> [Comb1] //&& KFR_ET_Report[Combination_Index] <> Comb2 && KFR_ET_Report[Combination_Index] <> Comb3)",
              "            , [NewUSD]",
              "",
              "            , SWITCH(TRUE()",
              "                , KFR_ET_Report[Combination_Index] = [Comb1]",
              "                    , [NewUSD] * (1 + [Comb1_shift])",
              "",
              "                //add more here.",
              "            )",
              "        )",
              ")",
              "",
              "",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD2]) * [TP_BusCount_1]",
              "                , [TP_Travellers_1]",
              "            )",
              "",
              "// Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD2]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc          "
            ],
            "lineageTag": "a16a1f7b-a4b4-4b01-93db-334cef0e6416"
          },
          {
            "name": "Pax_1_sim_v4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//including group size simulation.",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] //&& KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        // , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                        //     , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "    , \"NewUSD2\", ",
              "        if(KFR_ET_Report[Combination_Index] <> [Comb1] && KFR_ET_Report[Combination_Index] <> [Comb2] ",
              "            , [NewUSD]",
              "",
              "            , SWITCH(TRUE()",
              "                , KFR_ET_Report[Combination_Index] = [Comb1]",
              "                    , [NewUSD] * (1 + [Comb1_shift])",
              "                , KFR_ET_Report[Combination_Index] = [Comb2]",
              "                    , [NewUSD] * (1 + [Comb2_shift])",
              "",
              "                //add more here.",
              "            )",
              "        )",
              ")",
              "",
              "",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD2]) * [TP_BusCount_1] //dont need for min/max group. ",
              "                // , 20 //[TP_Travellers_1] //min, max, eller procentuellt addition.",
              "                // , [Min_Group] //* 1.20 //increasing travellers. bigger bus size.",
              "                , [Min_Group2]/100 * [TP_Travellers_1]",
              "            )",
              "",
              "",
              "// Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD2]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc          "
            ],
            "lineageTag": "e605c446-08ec-42a9-a45b-5377f7427c2f"
          },
          {
            "name": "Avg_BusSize_Min",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([TP_Travellers_1], [TP_BusCount_1]) * [Min_Group2]/100",
            "lineageTag": "1bbf5044-59fd-4635-84d7-aadcd6523149"
          },
          {
            "name": "Avg_BusSize_Max",
            "expression": "DIVIDE([TP_Travellers_1], [TP_BusCount_1]) * [Max_Group2]/100",
            "lineageTag": "621787ce-2a4e-4885-86de-249406ad8dbe"
          },
          {
            "name": "Pax_1_sim_Min",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//including group size simulation.",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] //&& KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        // , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                        //     , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "    , \"NewUSD2\", ",
              "        if(KFR_ET_Report[Combination_Index] <> [Comb1] && KFR_ET_Report[Combination_Index] <> [Comb2] ",
              "            , [NewUSD]",
              "",
              "            , SWITCH(TRUE()",
              "                , KFR_ET_Report[Combination_Index] = [Comb1]",
              "                    , [NewUSD] * (1 + [Comb1_shift])",
              "                , KFR_ET_Report[Combination_Index] = [Comb2]",
              "                    , [NewUSD] * (1 + [Comb2_shift])",
              "",
              "                //add more here.",
              "            )",
              "        )",
              ")",
              "",
              "",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD2]) * [TP_BusCount_1] //dont need for min/max group. ",
              "                // , [Min_Group2]/100 * [TP_Travellers_1]",
              "                , ([TP_Travellers_1] * [GroupSize_move])",
              "            )",
              "",
              "",
              "// Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD2]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc       "
            ],
            "lineageTag": "65d473c0-8dfc-44b1-952b-665edf3fe31e"
          },
          {
            "name": "Sim_Pax_Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "[Pax_1_sum_sim] - [Pax_1_sum]",
              "",
              "// SWITCH(TRUE()",
              "//     , [Min_Group] = 0 && [IfEmptySlicers] = 1, 0",
              "//     , [Pax_1_sum_sim] - [Pax_1_sum]",
              "// )"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "a3838336-04a3-4f42-ae9b-f14027f53f7f"
          },
          {
            "name": "LandCost_diff_sim",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "// Var Calc = [IfEmptySlicers]",
              "",
              "SWITCH(TRUE()",
              "    , [Min_Group] = 0 && [IfEmptySlicers] = 1, 0",
              "    , ([Pax_1_sum_sim] - [Pax_1_sum]) * [TP_Travellers_1]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "4571f3e6-70c2-4bc5-a1cc-b9903a61b1fa"
          },
          {
            "name": "Current_FX",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MySelection = SELECTEDVALUE(KFR_ET_Report[CurrencyCode])",
              "",
              "Var Calc =",
              "",
              "SUMX(",
              "    SUMMARIZE(",
              "        FILTER(DISTINCT(KFR_ET_Report), KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "",
              "        , KFR_ET_Report[CurrencyCode]",
              "        , KFR_ET_Report[Rate]",
              "    )",
              "    // , IF(MySelection = KFR_ET_Report[CurrencyCode], KFR_ET_Report[Rate])",
              "    , IF(ISFILTERED(KFR_ET_Report[CurrencyCode]) && MySelection = KFR_ET_Report[CurrencyCode], KFR_ET_Report[Rate])",
              ")",
              "",
              "Return Calc "
            ],
            "formatString": "#,0.00",
            "lineageTag": "9a7e04e2-28d1-45cb-9296-858bcf652321"
          },
          {
            "name": "Sim_FX",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MySelection = SELECTEDVALUE(KFR_ET_Report[CurrencyCode])",
              "",
              "Var MyCurr1 = LOOKUPVALUE(Live_azure_TopLevel[Curr_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var MyCurr2 = LOOKUPVALUE(Live_azure_TopLevel[Curr_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "// Var MyCurr1 = LOOKUPVALUE(Live_azure_TopLevel[Curr_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "// Var MyCurr1 = LOOKUPVALUE(Live_azure_TopLevel[Curr_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Var Calc =",
              "",
              "SUMX(",
              "    SUMMARIZE(",
              "        ",
              "        FILTER(DISTINCT(KFR_ET_Report), KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "",
              "        , KFR_ET_Report[CurrencyCode]",
              "        , KFR_ET_Report[Rate]",
              "    )",
              "    , IF(ISFILTERED(KFR_ET_Report[CurrencyCode]) && MySelection = KFR_ET_Report[CurrencyCode] && MySelection <> MyCurr1 && MySelection <> MyCurr2",
              "        , KFR_ET_Report[Rate]",
              "        ",
              "        , SWITCH(TRUE()",
              "            , ISFILTERED(KFR_ET_Report[CurrencyCode]) && KFR_ET_Report[CurrencyCode] = MyCurr1, (1 + [Curr1_shift]) * KFR_ET_Report[Rate]",
              "            , ISFILTERED(KFR_ET_Report[CurrencyCode]) && KFR_ET_Report[CurrencyCode] =  MyCurr2, (1 + [Curr2_shift]) * KFR_ET_Report[Rate]",
              "        )",
              "    )",
              ")",
              "",
              "Var Calc2 = IF(MySelection <> \"\", Calc, BLANK())",
              "",
              "Return Calc2"
            ],
            "formatString": "#,0.00",
            "lineageTag": "ad58e2ac-8c78-424a-bd07-ac8fcbbb6485"
          },
          {
            "name": "Sim_FX_test",
            "expression": [
              "",
              "",
              "Var MySelection = SELECTEDVALUE(KFR_ET_Report[CurrencyCode])",
              "Var Current_FX = [Current_FX]",
              "",
              "Var Calc = ",
              "    SWITCH(TRUE()",
              "        , MySelection <> BLANK() && Current_FX <> BLANK()",
              "            , SWITCH(TRUE()",
              "                , MySelection = [Curr1], ",
              "",
              "",
              "Return Calc",
              ""
            ],
            "lineageTag": "875410e1-76cc-4991-8bca-f51ff9106cf9"
          },
          {
            "name": "Pax_1_sim_Min_group",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//including group size simulation.",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] //&& KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        // , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                        //     , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "    , \"NewUSD2\", ",
              "        if(KFR_ET_Report[Combination_Index] <> [Comb1] && KFR_ET_Report[Combination_Index] <> [Comb2] ",
              "            , [NewUSD]",
              "",
              "            , SWITCH(TRUE()",
              "                , KFR_ET_Report[Combination_Index] = [Comb1]",
              "                    , [NewUSD] * (1 + [Comb1_shift])",
              "                , KFR_ET_Report[Combination_Index] = [Comb2]",
              "                    , [NewUSD] * (1 + [Comb2_shift])",
              "",
              "                //add more here.",
              "            )",
              "        )",
              ")",
              "",
              "",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD2]) //* [TP_BusCount_1] //dont need for min/max group. ",
              "                // , [Min_Group2]/100 * [TP_Travellers_1]",
              "                , [Min_Group]",
              "            )",
              "",
              "",
              "// Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [NewUSD]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [NewUSD2]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc          "
            ],
            "lineageTag": "040e7695-af1e-4e1c-b464-53ecdb0bdeda"
          },
          {
            "name": "Pax_1_sum_sim_Group",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyYear = VALUE(\"20\" & MID(SELECTEDVALUE(KFR_ET_DIM_Slicer1[Period]),2,2))",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [Pax_1_sim_Min_group] * [TP_Travellers_1]",
              "        )",
              "        , [TP_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "3460cc51-6481-4b07-b585-b64aff3593e0"
          },
          {
            "name": "LandCost_USD_1_sim",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Pax_1_sum_sim] * [My_Travellers_1]",
            "formatString": "#,0",
            "lineageTag": "d5324463-660b-43c7-ae98-210cc9f9f223"
          }
        ],
        "partitions": [
          {
            "name": "My_Measure-45ae9d8f-60fc-40ed-9c32-f1120f451844",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_39e4d5af-98f4-4320-bc8a-c23709c5e0c8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "13d4bc8d-b044-4ff2-8d42-33d8604104d3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "797670ab-ebc6-4a51-9c42-7b2062a4cafd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "daf7b843-0dd5-47c2-8cb5-d20647bf8eed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec52702e-5b35-4e79-9316-36dd30ebb210",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fb14f5e6-04de-4198-9d90-6227e22b9c26",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "85edecc4-b3d9-4002-8db8-e763b9111a4a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "feb35e7c-d701-4a0a-8674-73a6c0446723",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e09eb174-a7e1-40e9-8f3a-4e4a192a56e2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6d75065f-80e3-406c-a24d-17a0249bb727",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "37b7aec5-9288-45e1-b9fb-0fda0fd840b4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b9689418-fccc-4f88-8621-1abb02552829",
                "ordinal": 3
              }
            ],
            "lineageTag": "17c58028-16e8-4721-8004-339842441489"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cd96b278-03d9-482e-be90-3319819222d4",
        "partitions": [
          {
            "name": "DateTableTemplate_39e4d5af-98f4-4320-bc8a-c23709c5e0c8-0831b8c9-9422-4ce9-90a1-268f304120e1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Live_azure_TopLevel",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "98c9f893-c623-434a-8aab-c51850271181",
            "sourceColumn": "ID",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CompType_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0ae6c37-e3ab-4899-8c4d-7c4ff015cef6",
            "sourceColumn": "CompType_1",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CompType_1_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c672b27-3f6c-42ca-95a6-24344e5a66a8",
            "sourceColumn": "CompType_1_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "CompType_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3da8d2ff-6244-4f9b-afb7-9a5db3417fbb",
            "sourceColumn": "CompType_2",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CompType_2_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b8e6851-f0da-4372-b49a-03ef970d62d7",
            "sourceColumn": "CompType_2_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "CompType_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f04bb961-353b-4f98-917a-7a60b4807e21",
            "sourceColumn": "CompType_3",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CompType_3_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3ba39ce9-4f27-4343-92d4-f5581800824d",
            "sourceColumn": "CompType_3_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "CompType_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17706b4e-fc96-4d4c-b0d1-8b6c79f99829",
            "sourceColumn": "CompType_4",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "CompType_4_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9b0e556-4c41-4599-9dee-43622a0f8f98",
            "sourceColumn": "CompType_4_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "Curr_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feb23ad3-aec2-4051-bc64-d71309ad1623",
            "sourceColumn": "Curr_1",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Curr_1_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c03abe8a-9c89-4cdb-8d14-d4b55c6944ca",
            "sourceColumn": "Curr_1_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "Curr_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bda405f-77d2-42fa-8236-8358a30cb140",
            "sourceColumn": "Curr_2",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Curr_2_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d29fad9-58c9-4b27-8c9e-3bfb6e7f927e",
            "sourceColumn": "Curr_2_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "Curr_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a826cd8-b127-4f5d-9707-2d06ed224fd7",
            "sourceColumn": "Curr_3",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Curr_3_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c4beba75-8638-4163-9e60-3e2a099ac441",
            "sourceColumn": "Curr_3_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "Curr_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84b6e119-255e-48d0-8b2e-8bd033b317a0",
            "sourceColumn": "Curr_4",
            "sourceProviderType": "nvarchar(500)",
            "summarizeBy": "none"
          },
          {
            "name": "Curr_4_shift",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1d67440-10a0-4bb6-95b9-815d386100e5",
            "sourceColumn": "Curr_4_shift",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "bdbd5a40-1bf2-4a50-8b68-78b223e75f83",
        "partitions": [
          {
            "name": "Live_azure_TopLevel-b3e90299-d7d7-41cd-92c7-4dba0aa2b18f",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"tours-power-apps.database.windows.net\", \"TravelerAnalysis\", [Query=\"SELECT#(lf)      *#(lf)FROM TravelerAnalysis.dbo.KFR_B2S_TopLevel\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Azure_measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b11f16ab9f7b40dfaa3c74789050b8b7"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ab37d74b-e8c0-4b5a-b94e-c9afe52f65e8",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f5c51efd-d48d-4a45-babe-b63b19d67448",
        "measures": [
          {
            "name": "Curr1",
            "expression": [
              "",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(CurrencyTable[Currency_Index], CurrencyTable[CurrencyCode], MyCurr)",
              "// Var Calc = ",
              "//     SWITCH(TRUE()",
              "//         , MyCurr = \"AUD\", 1",
              "//         , MyCurr = \"EUR\", 2",
              "//         , MyCurr = \"GBP\", 3",
              "//         , MyCurr = \"USD\", 4",
              "//     )",
              "",
              "Return Calc   "
            ],
            "formatString": "0",
            "lineageTag": "8b9cd953-4a2b-4656-a296-a3af2f2a407f"
          },
          {
            "name": "Curr1_shift",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = LOOKUPVALUE(Live_azure_TopLevel[Curr_1_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Return Calc"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "66e907f2-84db-4f9b-8e6f-4dcc78345b83"
          },
          {
            "name": "Curr2",
            "expression": [
              "//LOOKUPVALUE(Live_azure_TopLevel[Curr_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(CurrencyTable[Currency_Index], CurrencyTable[CurrencyCode], MyCurr)",
              "",
              "// Var Calc = ",
              "//     SWITCH(TRUE()",
              "//         , MyCurr = \"AUD\", 1",
              "//         , MyCurr = \"EUR\", 2",
              "//         , MyCurr = \"GBP\", 3",
              "//         , MyCurr = \"USD\", 4",
              "//     )",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "9ee091f5-2084-400c-a5b2-0f75f779b8e7"
          },
          {
            "name": "Curr2_shift",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "LOOKUPVALUE(Live_azure_TopLevel[Curr_2_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "55a4a9ab-7c9a-4061-8305-a25deb9d8ffc"
          },
          {
            "name": "Curr3",
            "expression": [
              "",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_3], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(CurrencyTable[Currency_Index], CurrencyTable[CurrencyCode], MyCurr)",
              "",
              "// Var Calc = ",
              "//     SWITCH(TRUE()",
              "//         , MyCurr = \"AUD\", 1",
              "//         , MyCurr = \"EUR\", 2",
              "//         , MyCurr = \"GBP\", 3",
              "//         , MyCurr = \"USD\", 4",
              "//     )",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "0b473c09-5c2d-4bcc-986c-f995d2d0ce32"
          },
          {
            "name": "Curr3_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "LOOKUPVALUE(Live_azure_TopLevel[Curr_3_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              ""
            ],
            "lineageTag": "63f89837-5e29-4612-b249-1e788c70f189"
          },
          {
            "name": "Comb1",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(RegionCompTable[RegionComp_Index], RegionCompTable[RegionComp], MyCombination)",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "a0ca5c76-2899-48b6-81a6-f4f7f54591b6"
          },
          {
            "name": "Comb1_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = LOOKUPVALUE(Live_azure_TopLevel[CompType_1_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Return Calc"
            ],
            "lineageTag": "4707511b-897e-4924-b3d6-5d88ba44b75b"
          },
          {
            "name": "MaxID",
            "expression": [
              "",
              "",
              "",
              "Var MyMax = CALCULATE(MAX(Live_azure_TopLevel[ID]), ALL(Live_azure_TopLevel)) ",
              "Var CurrentId = SELECTEDVALUE(Live_azure_TopLevel[ID])",
              "",
              "Var Calc = ",
              "    SWITCH(TRUE()",
              "        , CurrentId = MyMax, 1",
              "        , 0",
              "    )",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "1a803267-01ce-4d98-bac0-bcc8572889e3"
          },
          {
            "name": "Comb2",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(RegionCompTable[RegionComp_Index], RegionCompTable[RegionComp], MyCombination)",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "b66e412f-611d-44ad-a2bc-42dfff4aa3f4"
          },
          {
            "name": "Comb2_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = LOOKUPVALUE(Live_azure_TopLevel[CompType_2_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Return Calc"
            ],
            "lineageTag": "4f8c92e9-6b89-4ecb-a44e-17a2c5b490a9"
          },
          {
            "name": "Comb3_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = LOOKUPVALUE(Live_azure_TopLevel[CompType_3_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Return Calc"
            ],
            "lineageTag": "e2a192b6-ad06-42e9-8ba1-4583e0f6d1a4"
          },
          {
            "name": "Comb4_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = LOOKUPVALUE(Live_azure_TopLevel[CompType_4_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Return Calc"
            ],
            "lineageTag": "a27cc941-c0a1-4e46-8847-787a94936787"
          },
          {
            "name": "Comb3",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_3], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(RegionCompTable[RegionComp_Index], RegionCompTable[RegionComp], MyCombination)",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "7aea0429-a344-482f-8fb2-4e31af8fbaba"
          },
          {
            "name": "Comb4",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_4], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(RegionCompTable[RegionComp_Index], RegionCompTable[RegionComp], MyCombination)",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "19474560-13cf-434c-b199-15324eb9094e"
          },
          {
            "name": "Curr4",
            "expression": [
              "",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_4], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "Var Calc = LOOKUPVALUE(CurrencyTable[Currency_Index], CurrencyTable[CurrencyCode], MyCurr)",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "63ed2b23-0fc1-4b2f-b7fc-805cab1ef3b8"
          },
          {
            "name": "Curr4_shift",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "LOOKUPVALUE(Live_azure_TopLevel[Curr_4_shift], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              ""
            ],
            "lineageTag": "a761dd6e-f161-481e-9b82-0f7bb569c3ab"
          },
          {
            "name": "Curr1_view",
            "expression": [
              "",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Var MyShift = ",
              "    SWITCH(TRUE()",
              "        , [Curr1_shift] > 0, \" (+\" & [Curr1_shift] * 100 & \"%)\"",
              "        , \" (\" & [Curr1_shift] * 100 & \"%)\"",
              "    )",
              "",
              "Var Calc = MyCurr & MyShift",
              "",
              "Var Calc2 = ",
              "    SWITCH(TRUE()",
              "        , ISBLANK(MyCurr), BLANK()",
              "        , Calc",
              "    )",
              "",
              "Return Calc "
            ],
            "lineageTag": "47da2430-3dff-4e87-b94d-c6068f1e8909"
          },
          {
            "name": "Curr2_view",
            "expression": [
              "",
              "",
              "Var MyCurr = LOOKUPVALUE(Live_azure_TopLevel[Curr_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "",
              "Var MyShift = ",
              "    SWITCH(TRUE()",
              "        , [Curr2_shift] > 0, \" (+\" & [Curr2_shift] * 100 & \"%)\"",
              "        , \" (\" & [Curr2_shift] * 100 & \"%)\"",
              "    )",
              "",
              "Var Calc = MyCurr & MyShift",
              "",
              "Var Calc2 = ",
              "    SWITCH(TRUE()",
              "        , ISBLANK(MyCurr), BLANK()",
              "        , Calc",
              "    )",
              "",
              "Return Calc2 "
            ],
            "lineageTag": "da22b350-a708-4f91-bdfe-ecd3932e6853"
          },
          {
            "name": "Comb1_view",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_1], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "// Var Calc = MyCombination & \" (\" & [Comb1_shift] * 100 & \"%)\"",
              "",
              "Var MyShift = ",
              "    SWITCH(TRUE()",
              "        , [Comb1_shift] > 0, \" (+\" & [Comb1_shift] * 100 & \"%)\"",
              "        , \" (\" & [Comb1_shift] * 100 & \"%)\"",
              "    )",
              "",
              "Var Calc = MyCombination & MyShift",
              "",
              "Var Calc2 = ",
              "    SWITCH(TRUE()",
              "        , ISBLANK(MyCombination), BLANK()",
              "        , Calc",
              "    )",
              "",
              "Return Calc2 "
            ],
            "lineageTag": "eeb56758-3459-4745-894e-7f1dff534833"
          },
          {
            "name": "Comb2_view",
            "expression": [
              "",
              "",
              "Var MyCombination = LOOKUPVALUE(Live_azure_TopLevel[CompType_2], Live_azure_TopLevel[ID], MAX(Live_azure_TopLevel[ID]))",
              "// Var Calc = MyCombination & \" (\" & [Comb2_shift] * 100 & \"%)\"",
              "",
              "Var MyShift = ",
              "    SWITCH(TRUE()",
              "        , [Comb2_shift] > 0, \" (+\" & [Comb2_shift] * 100 & \"%)\"",
              "        , \" (\" & [Comb2_shift] * 100 & \"%)\"",
              "    )",
              "",
              "Var Calc = MyCombination & MyShift",
              "",
              "Var Calc2 = ",
              "    SWITCH(TRUE()",
              "        , ISBLANK(MyCombination), BLANK()",
              "        , Calc",
              "    )",
              "",
              "Return Calc2 "
            ],
            "lineageTag": "87a69225-4379-451e-a695-a514c20a6809"
          }
        ],
        "partitions": [
          {
            "name": "Azure_measures-3b95ddca-942c-457a-9d34-4a6b85bbd0f6",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Z_GroupSize",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8b41d062a648458998281b34ff8bcf32"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f00dacee-f6a4-47bb-a644-21a9cd3f8529",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d1a2b7d7-4b87-4a59-8a25-03afac3142b9",
        "measures": [
          {
            "name": "Min_Group",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "MIN(Z_GroupSize[Value])",
            "formatString": "0.00",
            "lineageTag": "01f89266-4772-4e74-9ec0-e2e52b08708c"
          },
          {
            "name": "Max_Group",
            "expression": "MAX(Z_GroupSize[Value])",
            "formatString": "0",
            "lineageTag": "d5ce647a-a6d8-4d1a-a361-349b58a1087c"
          },
          {
            "name": "GroupSize_move",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "// Var MyAvg = CALCULATE(Used_Measures[Avg_BusSize_1], ",
              "",
              "SWITCH(TRUE()",
              "    , Z_GroupSize[Min_Group] = 0, 1",
              "    // , DIVIDE(Z_GroupSize[Min_Group], Used_Measures[Avg_BusSize_1])",
              "    // , DIVIDE(Z_GroupSize[Min_Group], 31.87)",
              "    ",
              "    , DIVIDE(Z_GroupSize[Min_Group], [Calc_bus_avg]) //Calc_bus_avg does the whole ET. resets filters. ",
              "    // , DIVIDE(Z_GroupSize[Min_Group], [Avg_BusSize_1])",
              ")"
            ],
            "lineageTag": "007cd89d-331a-4250-82e9-a56441d2d106"
          },
          {
            "name": "GroupSize_move(%)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[GroupSize_move] - 1",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2154c153-ee16-4c22-938e-395c6f57007f"
          },
          {
            "name": "GroupFilter",
            "expression": [
              "",
              "",
              "Var MyValue = [Min_Group]",
              "",
              "Var MyCurrent = SELECTEDVALUE(Z_GroupSize[Value])",
              "",
              "",
              "Var Calc = ",
              "    SWITCH(TRUE()",
              "        , MyCurrent > 20 && MyCurrent < 40, 1",
              "        // , MyCurrent > MyValue * 0.8 && MyCurrent < MyValue * 1.2, 1",
              "        , 0",
              "    )",
              "",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "f9210321-8958-48bf-b46b-2d158a6977f6"
          },
          {
            "name": "IfEmpty",
            "expression": "IF([Min_Group] = 0, \"Simulation OFF\", \"Simulation ON\")",
            "lineageTag": "2083843e-b0e1-4345-9833-b03bcbb99e42"
          }
        ],
        "partitions": [
          {
            "name": "Z_GroupSize-091010bc-42c3-4dd2-8090-aafb91848fc5",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0,50,0.01)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Z_GroupSize_2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1f15d3bcf2694b81a56ccfdfab4ce944"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3701d81c-1de4-4cdd-8d54-ec5d96476f21",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f3434931-f9f8-4eef-b5e0-7bda4285468c",
        "measures": [
          {
            "name": "Min_Group2",
            "expression": "MIN(Z_GroupSize_2[Value])",
            "formatString": "0",
            "lineageTag": "9f27b6ff-3989-4e38-9a58-c4e516fa3036"
          },
          {
            "name": "Max_Group2",
            "expression": "MAX(Z_GroupSize_2[Value])",
            "formatString": "0",
            "lineageTag": "18566555-d711-4dc1-b5ec-db1702ce30b4"
          }
        ],
        "partitions": [
          {
            "name": "Z_GroupSize_2-f701448a-e735-46d2-9d53-aa187669193d",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(50,150,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "FilterPane",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5547b97d20f04703a08e7ef60bb73310"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0d5161f5-5796-4b11-b4b2-7f5268a1fa7f",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b1f29236-2603-42e1-a976-8ce3d038a449",
        "measures": [
          {
            "name": "Current_Product",
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[ProductMarketCode], \"ALL\")",
            "lineageTag": "f7d303ba-f94c-49ab-b5a7-77c9b40df3c6"
          },
          {
            "name": "Current_Business",
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[BusinessUnit], \"ALL\")",
            "lineageTag": "275e4acb-8f82-4a7e-8812-2fa4ba09d4fd"
          },
          {
            "name": "Current_Region",
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[TourRegionCode], \"ALL\")",
            "lineageTag": "17a7df53-a433-4be8-b937-f3f21773a98d"
          },
          {
            "name": "Current_TourCode",
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[TourCode], \"ALL\")",
            "lineageTag": "7b1b9f39-1648-4eae-93d9-43ff0694f82c"
          },
          {
            "name": "Current_TourVersion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[TourVersionCode], \"ALL\")",
            "lineageTag": "33e7f7f8-c3c8-46d5-9640-58afe592a204"
          },
          {
            "name": "Current_Season",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_TravelPattern[BudgetSeasonNum], \"ALL\")",
            "lineageTag": "a2237c87-7ccb-40b8-9693-08ddb84f0d9d"
          },
          {
            "name": "Current_ComptypeCode",
            "expression": "SELECTEDVALUE(KFR_ET_Report[CompTypeCode], \"ALL\")",
            "lineageTag": "5bfaae22-a4e9-42d3-a738-bbf6ac435451"
          },
          {
            "name": "Current_LookupCode",
            "expression": "SELECTEDVALUE(KFR_ET_Report[LookupCode], \"ALL\")",
            "lineageTag": "96744b00-a922-4c9c-a58b-b5d6bdcb731c"
          }
        ],
        "partitions": [
          {
            "name": "FilterPane-121bf60c-304c-416b-8ee4-5a233e6e8149",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Used_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9cf6cc27343545749bdb495f76e7b912"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "863ffe9a-8221-44a1-ac79-cd40c1847ae3",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "77741f53-bd0c-41ac-81a9-a61ca72d3c61",
        "measures": [
          {
            "name": "Pax_1_sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR)",
              "        , [Pax_1] * [My_Travellers_1]",
              "        )",
              "        , [My_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "",
              "Return Calc"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f49cfdcf-0d54-4d20-b590-360be0cc06b2"
          },
          {
            "name": "My_Travellers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(KFR_ET_TravelPattern[Travellers])",
            "lineageTag": "72cfbcb1-52fa-45f0-bdf7-9376039d1ee1"
          },
          {
            "name": "TP_Travellers_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//_measures[My_Travellers]= My_Travellers = SUM(KFR_ET_TravelPattern[Travellers])",
              "Var MyYear = VALUE(\"20\" & MID(SELECTEDVALUE(KFR_ET_DIM_Slicer1[Period]),2,2))",
              "Var KFR_1 = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = KFR_1 && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [My_Travellers]",
              "    )",
              " ",
              "Return Calc  "
            ],
            "formatString": "#,0",
            "lineageTag": "6b9ba8e7-44bf-4151-ab1e-18f87b4fff9a"
          },
          {
            "name": "TP_BusCount_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//_measures[My_Travellers]= My_Travellers = SUM(KFR_ET_TravelPattern[Travellers])",
              "Var MyYear = VALUE(\"20\" & MID(SELECTEDVALUE(KFR_ET_DIM_Slicer1[Period]),2,2))",
              "Var KFR_1 = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = KFR_1 && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [My_BusCount]",
              "    )",
              " ",
              "Return Calc  "
            ],
            "formatString": "#,0",
            "lineageTag": "3481e6b0-ba1e-45fd-a491-f3690aa5f57a"
          },
          {
            "name": "My_BusCount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(KFR_ET_TravelPattern[BusCount])",
            "lineageTag": "9ffee85c-c4fc-47dd-82ff-cda203667a50"
          },
          {
            "name": "Pax_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "    )",
              "",
              "// Var USD_calc_group = ",
              "//             DIVIDE(",
              "//                 SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [LocalTotal_USD]) * [My_BusCount_1]",
              "//                 , [My_Travellers_1]",
              "//             )",
              "",
              "Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [LocalTotal_USD_group]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [LocalTotal_USD]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc        "
            ],
            "formatString": "#,0",
            "lineageTag": "1f943df6-fd2a-4a49-b4b7-5bc0aa4ca1c1"
          },
          {
            "name": "Pax_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "Var MyTable = ",
              "",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "    )",
              "",
              "// Var USD_calc_group = ",
              "//             DIVIDE(",
              "//                 SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [LocalTotal_USD]) * [My_BusCount_1]",
              "//                 , [My_Travellers_1]",
              "//             )",
              "",
              "Var USD_calc_group = SUMX(FILTER(MyTable, [IsPerGroup] = TRUE()), [LocalTotal_USD_group]) ",
              "Var USD_calc_pax = SUMX(FILTER(MyTable, [IsPerGroup] = FALSE()), [LocalTotal_USD]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc        "
            ],
            "lineageTag": "5014c1aa-9c57-483f-b7f9-0be3015eb799"
          },
          {
            "name": "Pax_2_sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR)",
              "        , [Pax_2] * [My_Travellers_2]",
              "        )",
              "        , [My_Travellers_2] //My Filtered volume. ",
              "    )",
              "",
              "Return Calc"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ee9f193b-89d5-48e1-a28a-f563d2cdaf94"
          },
          {
            "name": "TP_Travellers_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//_measures[My_Travellers]= My_Travellers = SUM(KFR_ET_TravelPattern[Travellers])",
              "Var MyYear = VALUE(\"20\" & Right(SELECTEDVALUE(KFR_ET_DIM_Slicer2[Period]),2))",
              "Var KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = KFR && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [My_Travellers]",
              "    )",
              " ",
              "Return Calc  "
            ],
            "formatString": "#,0",
            "lineageTag": "d2074b11-c7b9-4466-b66b-1f6892e6c5a6"
          },
          {
            "name": "Pax_diff_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Pax_2_sum] - [Pax_1_sum]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b94fdb40-edd8-4024-9c79-d1fcb4cc90ca"
          },
          {
            "name": "LandCost_USD_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Pax_1_sum] * [My_Travellers_1]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e5fc08ec-be91-43ca-ba97-0dce94f02a44"
          },
          {
            "name": "LandCost_USD_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Pax_2_sum] * [My_Travellers_2]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fc2e42a2-8a05-49d3-8f70-1cb0e2a441e4"
          },
          {
            "name": "LandCost_diff_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[LandCost_USD_2] - [LandCost_USD_1]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "81feabd5-ad2b-49eb-a4d7-830097e9420f"
          },
          {
            "name": "My_BusCount_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[BusCount]",
              "            )",
              "        , KFR_ET_Report[BusCount]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0.00",
            "lineageTag": "d97905ca-eef5-40b6-8815-9bb05e8a937d"
          },
          {
            "name": "My_Travellers_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[SLICER_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[Travellers]",
              "            )",
              "        , KFR_ET_Report[Travellers]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "lineageTag": "ca3b7848-3f31-4ba7-b76c-82ddf3ebc432"
          },
          {
            "name": "Avg_BusSize_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([TP_Travellers_1], [TP_BusCount_1])",
            "formatString": "#,0.000",
            "lineageTag": "b2f1374f-8486-46d8-a298-b18024bf2cdd"
          },
          {
            "name": "XX_Variable_Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var MyMeasure = SELECTEDVALUE(Slicer_options[Value])",
              "",
              "// Var MyMeasure = \"LandCost\"",
              "",
              "Var Calc = ",
              "",
              "//Measure = LandCost.",
              "    SWITCH(TRUE()",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BusinessUnit\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BusinessUnit]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BusinessUnit[BusinessUnit])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CompTypeCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CompTypeCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CompTypeCode[CompTypeCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CurrencyCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CurrencyCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CurrencyCode[CurrencyCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"LookupCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[LookupCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_LookupCode[LookupCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourCode[TourCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourRegionCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourRegionCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourRegionCode[TourRegionCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"ProductMarketCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[ProductMarketCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_ProductMarketCode[ProductMarketCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BudgetSeasonNum\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BudgetSeasonNum]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BudgetSeasonNum[BudgetSeasonNum])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"StartLocationCountryName\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[StartLocationCountryName]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_StartCountry[StartLocationCountryName])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourTypeCode\" && MyMeasure = \"Total Cost\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourTypeCode]",
              "                        , \"USD\", [LandCost_USD_2]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourTypeCode[TourTypeCode])",
              "            )",
              "",
              "//Adding LandCost Diff ",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BusinessUnit\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BusinessUnit]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BusinessUnit[BusinessUnit])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CompTypeCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CompTypeCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CompTypeCode[CompTypeCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CurrencyCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CurrencyCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CurrencyCode[CurrencyCode]) //fix currency dimension",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"LookupCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[LookupCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_LookupCode[LookupCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourCode[TourCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourRegionCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourRegionCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourRegionCode[TourRegionCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"ProductMarketCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[ProductMarketCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_ProductMarketCode[ProductMarketCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BudgetSeasonNum\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BudgetSeasonNum]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BudgetSeasonNum[BudgetSeasonNum])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"StartLocationCountryName\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[StartLocationCountryName]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_StartCountry[StartLocationCountryName])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourTypeCode\" && MyMeasure = \"Cost Diff\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourTypeCode]",
              "                        , \"USD\", [LandCost_diff_USD]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourTypeCode[TourTypeCode])",
              "            )",
              "",
              "",
              "//Measure = Pax price.",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BusinessUnit\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BusinessUnit]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BusinessUnit[BusinessUnit])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CompTypeCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CompTypeCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CompTypeCode[CompTypeCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"CurrencyCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[CurrencyCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_CurrencyCode[CurrencyCode]) //fix",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"LookupCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[LookupCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_LookupCode[LookupCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourCode[TourCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourRegionCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourRegionCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourRegionCode[TourRegionCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"ProductMarketCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[ProductMarketCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_ProductMarketCode[ProductMarketCode])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"BudgetSeasonNum\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[BudgetSeasonNum]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_BudgetSeasonNum[BudgetSeasonNum])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"StartLocationCountryName\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[StartLocationCountryName]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_StartCountry[StartLocationCountryName])",
              "            )",
              "",
              "        , SELECTEDVALUE(Dim_MultipleAxis[Axis]) = \"TourTypeCode\" && MyMeasure = \"Cost per Traveler\"",
              "            ,",
              "            CALCULATE(",
              "                SUMX(",
              "                    SUMMARIZE(KFR_ET_Report",
              "                        , KFR_ET_Report[TourTypeCode]",
              "                        , \"USD\", [Pax_2_sum]",
              "                    )",
              "                , [USD]",
              "                )",
              "                , USERELATIONSHIP(Dim_MultipleAxis[ProductMarketCode], Dim_TourTypeCode[TourTypeCode])",
              "            )",
              "",
              "",
              "",
              "",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "lineageTag": "994fe33e-2746-48b4-a5ec-642f839156bf"
          },
          {
            "name": "XX_Top_Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Topx = TopX_slicer[Topx_Slicer]",
              "Var MyOrder = Slicer_order[Slicer_order]",
              "",
              "// Var Topx = 7",
              "// Var MyOrder = \"Descending\"",
              "",
              "Var Calc = ",
              "",
              "    SWITCH(TRUE()",
              "    , MyOrder = \"Ascending\"",
              "        , SUMX(",
              "            FILTER(VALUES(Dim_MultipleAxis[ProductMarketCode])",
              "                , IF(",
              "                    RANKX(ALL(Dim_MultipleAxis[ProductMarketCode]), [XX_Variable_Measure], , ASC, Dense ) <= Topx",
              "                    , [XX_Variable_Measure]",
              "                    , BLANK()",
              "                )",
              "            )",
              "            , [XX_Variable_Measure]",
              "        )",
              "",
              "    , MyOrder = \"Descending\"",
              "        , SUMX(",
              "        FILTER(VALUES(Dim_MultipleAxis[ProductMarketCode])",
              "            , IF(",
              "                RANKX(ALL(Dim_MultipleAxis[ProductMarketCode]), [XX_Variable_Measure], , DESC, Dense ) <= Topx",
              "                , [XX_Variable_Measure]",
              "                , BLANK()",
              "            )",
              "        )",
              "        , [XX_Variable_Measure]",
              "        )",
              "",
              "    , MyOrder = \"Absolute\"",
              "        , SUMX(",
              "        FILTER(VALUES(Dim_MultipleAxis[ProductMarketCode])",
              "            , IF(",
              "                RANKX(ALL(Dim_MultipleAxis[ProductMarketCode]), ABS([XX_Variable_Measure]), , DESC, Dense ) <= Topx",
              "                , [XX_Variable_Measure]",
              "                , BLANK()",
              "            )",
              "        )",
              "        , [XX_Variable_Measure]",
              "        )",
              "    )",
              "",
              "Return Calc "
            ],
            "lineageTag": "0e2eb909-3c97-48ca-b393-1dd579831c77"
          },
          {
            "name": "My_Travellers_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[Travellers]",
              "            )",
              "        , KFR_ET_Report[Travellers]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "9273ba2d-f181-4b8b-bf83-3c12681d164f"
          },
          {
            "name": "My_BusCount_2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[BusCount]",
              "            )",
              "        , KFR_ET_Report[BusCount]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0.00",
            "lineageTag": "a07d6338-c755-4699-b7c1-8be5d677ed00"
          },
          {
            "name": "Calc_bus_avg",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = CALCULATE([Avg_BusSize_1], FILTER(all(KFR_ET_Report), KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX))",
              "",
              "// Var Calc = CALCULATE(Used_Measures[Avg_BusSize_1], REMOVEFILTERS(KFR_ET_TravelPattern[ProductMarketCode], KFR_ET_TravelPattern[BusinessUnit],KFR_ET_TravelPattern[TourRegionCode]))",
              "",
              "Return Calc"
            ],
            "lineageTag": "0b5a0fa3-2d35-493a-8f84-082f754bbe8d"
          },
          {
            "name": "IfEmptySlicers",
            "expression": [
              "",
              "",
              "SWITCH(TRUE()",
              "    , [Curr1_shift] = BLANK() && [Curr2_shift] = BLANK() && [Comb1_shift] = BLANK() && [Comb2_shift] = BLANK(), 1",
              "    , 0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "46e53c78-9eec-4d7b-82ee-0407eec62048"
          },
          {
            "name": "My_BusSize_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([My_Travellers_1], [MY_BusCount_1])",
            "lineageTag": "5c298ceb-d44a-4b9e-afda-b0200aa2467b"
          },
          {
            "name": "My_BusSize_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([My_Travellers_2], [MY_BusCount_2])",
            "lineageTag": "d52f7fd8-8698-4e88-90d9-08ea24bbf511"
          },
          {
            "name": "My_BusShift",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "SWITCH(TRUE()",
              "    , DIVIDE([My_BusSize_2], Used_Measures[My_BusSize_1]) <> 0",
              "        , DIVIDE([My_BusSize_2], Used_Measures[My_BusSize_1]) - 1",
              "    , 0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e3e5df0d-40fe-4807-ae12-f709a9205afe"
          },
          {
            "name": "BusEffect_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var Calc = DIVIDE([GroupCost_2], (1 + [My_BusShift])) - [GroupCost_2]",
              "",
              "Return Calc "
            ],
            "lineageTag": "6dfbca84-0247-48da-ad9f-7ef0cc3252c6"
          },
          {
            "name": "GroupCost_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([LandCost_USD_2], KFR_ET_Report[IsPerGroup] = TRUE())",
            "lineageTag": "53ad10e8-3d1e-4cf3-a410-941804eba401"
          },
          {
            "name": "GroupCost_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([LandCost_USD_1], KFR_ET_Report[IsPerGroup] = TRUE())",
            "lineageTag": "1cb138e3-ae94-4771-be98-6431d6ac5a78"
          },
          {
            "name": "PaxCost_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([LandCost_USD_2], KFR_ET_Report[IsPerGroup] = FALSE())",
            "lineageTag": "09e16861-f4a6-43f6-bbff-bf2fbc11037e"
          },
          {
            "name": "PaxCost_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([LandCost_USD_1], KFR_ET_Report[IsPerGroup] = FALSE())",
            "lineageTag": "c5855ee2-07b0-4de7-8958-bcc02e4bac51"
          },
          {
            "name": "TourDuration_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR)",
              "        , [TourDuration] * [My_Travellers_1]",
              "        )",
              "        , [My_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "Return Calc"
            ],
            "formatString": "#,0.0000",
            "lineageTag": "11051755-c020-4dbb-8c8e-8188f1bef0ba"
          },
          {
            "name": "TourDuration_2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR)",
              "        , [TourDuration] * [My_Travellers_2]",
              "        )",
              "        , [My_Travellers_2] //My Filtered volume. ",
              "    )",
              "",
              "Return Calc"
            ],
            "formatString": "#,0.0000",
            "lineageTag": "63d64e4c-a7a6-4aeb-95ca-60918561a713"
          },
          {
            "name": "My_Volume_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "",
              "            --> adding these two lines for same lookupcode multiple this in the TourSpec.",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[BusCount]",
              "            , KFR_ET_Report[Travellers]",
              "            , KFR_ET_Report[Quantity]",
              "            , \"Volume\", ",
              "                        IF(KFR_ET_Report[IsPerGroup] = FALSE() ",
              "                        , KFR_ET_Report[Quantity] * KFR_ET_Report[Travellers]",
              "                        , KFR_ET_Report[Quantity] * KFR_ET_Report[BusCount]",
              "                        )",
              "            )",
              "        // , KFR_ET_Report[BusCount]",
              "        , [Volume]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "f6234247-cbf0-4525-879c-1ba153411069"
          },
          {
            "name": "My_Volume_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "",
              "            --> adding these two lines for same lookupcode multiple this in the TourSpec.",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CompStartDay]",
              "",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[BusCount]",
              "            , KFR_ET_Report[Travellers]",
              "            , KFR_ET_Report[Quantity]",
              "            , \"Volume\", ",
              "                        IF(KFR_ET_Report[IsPerGroup] = FALSE() ",
              "                        , KFR_ET_Report[Quantity] * KFR_ET_Report[Travellers]",
              "                        , KFR_ET_Report[Quantity] * KFR_ET_Report[BusCount]",
              "                        )",
              "            )",
              "        // , KFR_ET_Report[BusCount]",
              "        , [Volume]",
              "    )",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "feabfb26-66fb-4743-ba5c-8a327543e446"
          },
          {
            "name": "PricePerDay_1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Pax_1_sum], [TourDuration_1])",
            "formatString": "#,0.0000",
            "lineageTag": "3f4849d0-888d-448a-bd07-6ee2b3787aeb"
          },
          {
            "name": "PricePerDay_2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Pax_2_sum], [TourDuration_2])",
            "formatString": "#,0.0000",
            "lineageTag": "42dea90a-e9c6-4164-b8cf-70459ffd4e54"
          },
          {
            "name": "PaxCost_person_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([PaxCost_1], [My_Travellers_1])",
            "lineageTag": "fad7b3c0-0ffb-48c3-aa5f-1d27d2911bf1"
          },
          {
            "name": "PaxCost_person_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([PaxCost_2], [My_Travellers_2])",
            "lineageTag": "9b2cee11-7ee5-49ac-b5e3-67877fbafa3f"
          },
          {
            "name": "GroupCost_person_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([GroupCost_1], [My_Travellers_1])",
            "lineageTag": "3a5a2470-5bfc-419b-8ea9-b58dce93b7db"
          },
          {
            "name": "GroupCost_person_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([GroupCost_2], [My_Travellers_2])",
            "lineageTag": "21edee87-69b4-408d-82f1-6ad322b31cfa"
          },
          {
            "name": "Land1_precalc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = ",
              "    CALCULATE(SUM(KFR_ET_Report[USD_cost_precalc])",
              "        , KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR ",
              "        && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod ",
              "        && KFR_ET_Report[My_FX_Index] = My_FX",
              "    )",
              "",
              "",
              "Var Calc2 = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR)",
              "        , [Pax_1] * [My_Travellers_1]",
              "        )",
              "        , [My_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "841eff19-4be7-4797-9e84-d8c4df0de6af"
          },
          {
            "name": "Pax1_precalc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Land1_precalc], [My_Travellers_1])",
            "formatString": "#,0.00",
            "lineageTag": "18189312-220a-49ff-a316-4629cd251cd4"
          },
          {
            "name": "My_PayingPax_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[PayingPax]",
              "            )",
              "        , KFR_ET_Report[PayingPax]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "lineageTag": "c7680084-65c6-4749-91d6-122eaa525bc2"
          },
          {
            "name": "My_PayingPax_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer2[Slicer_KFR_2]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer2[Slicer_Periods_2]",
              "Var My_FX = KFR_ET_DIM_Slicer2[Slicer_FX_2]",
              "",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX)",
              "            , KFR_ET_Report[TP_key_ext_unique]",
              "            , KFR_ET_Report[PayingPax]",
              "            )",
              "        , KFR_ET_Report[PayingPax]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "lineageTag": "5764f243-7c12-42f1-b431-2fab4629b57a"
          }
        ],
        "partitions": [
          {
            "name": "Used_Measures-2d63b215-b0bc-46fa-a538-95cc901c5d72",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "TopX_slicer",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "444dc5e9d11e47c8be7d987523f02c1c"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "01c2825a-8b91-46da-b527-b3a2ce63b6d1",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "555a6e5d-c4bd-4b5e-aed8-f3b2263e67df",
        "measures": [
          {
            "name": "Topx_Slicer",
            "expression": "MIN(TopX_slicer[Value])",
            "formatString": "0",
            "lineageTag": "1faa05b3-6493-4cac-8f7f-58599759347f"
          }
        ],
        "partitions": [
          {
            "name": "TopX_slicer-3388ef6e-17f1-498a-be9d-14ac15025f50",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1,100,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Slicer_options",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "75eb70bd0ebb42d189f28b6f13889fc4"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bf22e181-3f3a-4d64-a417-d6f34669502b",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "89a16d8f-adfe-4c46-aa6d-6e43d031554d",
        "partitions": [
          {
            "name": "Slicer_options-60c1ee28-896b-4156-9995-72f2cd5c0076",
            "mode": "import",
            "source": {
              "expression": "{\"Cost per Traveler\", \"Total Cost\", \"Cost Diff\", \"TourCode Diff\", \"Group Cost Diff\", \"Pax Cost Diff\"}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Slicer_order",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a8e948d92b494d87ae245751ac61e750"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5d083e9b-289b-4f4b-8aab-2ba58e5263db",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "949cdfdf-935e-4b9c-bd36-5578ccbd52f5",
        "measures": [
          {
            "name": "Slicer_order",
            "expression": "SELECTEDVALUE(Slicer_order[Value])",
            "lineageTag": "018d6c8d-1570-49a6-bec6-3dadde2f3097"
          }
        ],
        "partitions": [
          {
            "name": "Slicer_order-7749d7c3-0c5b-4052-8ce1-f5e3df70f320",
            "mode": "import",
            "source": {
              "expression": "{\"Ascending\", \"Descending\", \"Absolute\" }",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_MultipleAxis",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0a6a443547334cfa9ba3636d021d0f66"
          }
        ],
        "columns": [
          {
            "name": "Axis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8217aad6-216c-42aa-b592-7504acef5b34",
            "sourceColumn": "[Axis]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ProductMarketCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c3e325a-a304-4b6e-a8c5-ac8d2e59a7c0",
            "sourceColumn": "[ProductMarketCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c16d2ec3-8c33-4a2d-a380-487592fddd8a",
        "partitions": [
          {
            "name": "Dim_MultipleAxis-15ed872c-8482-4f7e-8a07-4c5a83e6f9d6",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "UNION(",
                "    SELECTCOLUMNS(Dim_ProductMarketCode, \"ProductMarketCode\", Dim_ProductMarketCode[ProductMarketCode], \"Axis\", \"ProductMarketCode\")",
                "    , SELECTCOLUMNS(Dim_TourTypeCode, \"TourTypeCode\", Dim_TourTypeCode[TourTypeCode], \"Axis\", \"TourTypeCode\")",
                "    , SELECTCOLUMNS(Dim_BusinessUnit, \"BusinessUnit\", Dim_BusinessUnit[BusinessUnit], \"Axis\", \"BusinessUnit\")",
                "    , SELECTCOLUMNS(Dim_TourRegionCode, \"TourRegionCode\", Dim_TourRegionCode[TourRegionCode], \"Axis\", \"TourRegionCode\")",
                "    , SELECTCOLUMNS(Dim_TourCode, \"TourCode\", Dim_TourCode[TourCode], \"Axis\", \"TourCode\")",
                "    , SELECTCOLUMNS(Dim_StartCountry, \"StartLocationCountryName\", Dim_StartCountry[StartLocationCountryName], \"Axis\", \"StartLocationCountryName\")",
                "    , SELECTCOLUMNS(Dim_BudgetSeasonNum, \"BudgetSeasonNum\", Dim_BudgetSeasonNum[BudgetSeasonNum], \"Axis\", \"BudgetSeasonNum\") ",
                "    , SELECTCOLUMNS(Dim_CurrencyCode, \"CurrencyCode\", Dim_CurrencyCode[CurrencyCode], \"Axis\", \"CurrencyCode\")",
                "",
                "    , SELECTCOLUMNS(Dim_CompTypeCode, \"CompTypeCode\", Dim_CompTypeCode[CompTypeCode], \"Axis\", \"CompTypeCode\")",
                "    , SELECTCOLUMNS(Dim_LookupCode, \"LookupCode\", Dim_LookupCode[LookupCode], \"Axis\", \"LookupCode\")",
                "",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_ProductMarketCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "db0038bf178c4fdaa964f97570c364da"
          }
        ],
        "columns": [
          {
            "name": "ProductMarketCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "59df0936-65a5-4358-8aa8-e6fac80b1e63",
            "sourceColumn": "KFR_ET_Report[ProductMarketCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c37105ce-bc73-480e-87c1-5e6b511453fd",
        "partitions": [
          {
            "name": "Dim_ProductMarketCode-af64b600-6c48-4557-b5cc-2351c1979399",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[ProductMarketCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_TourTypeCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bc09d7d29c3d4a99a08b7f107ecf79b2"
          }
        ],
        "columns": [
          {
            "name": "TourTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "60a47666-b6c9-44b6-ab91-af709b9bc5ce",
            "sourceColumn": "KFR_ET_Report[TourTypeCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1bed4b1a-456f-4bcb-8050-b4c3ffc738a8",
        "partitions": [
          {
            "name": "Dim_TourTypeCode-5c07f646-1af2-443c-9885-4d5e9b4a14ba",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[TourTypeCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_BusinessUnit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "892fa8ac2d434622995ad2ef519ee133"
          }
        ],
        "columns": [
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "39f5c6bf-cd9c-429e-9caf-e1f799a19231",
            "sourceColumn": "KFR_ET_Report[BusinessUnit]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "52a1c0af-c086-4014-98f6-bff5fde8a9b6",
        "partitions": [
          {
            "name": "Dim_BusinessUnit-07567d9b-7b7f-418f-86e3-4d8d9f1384f7",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[BusinessUnit])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_TourRegionCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b4e055c64c5b4e7ea9b0880c1bc01dd5"
          }
        ],
        "columns": [
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bab53ff4-6f5b-47be-9648-c4c79fc50992",
            "sourceColumn": "KFR_ET_Report[TourRegionCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9e37f0a1-cd44-44e9-b284-be1f59e942b7",
        "partitions": [
          {
            "name": "Dim_TourRegionCode-bdb7816a-b7aa-4263-9318-58a3ec64ca61",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[TourRegionCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_TourCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9875878bed9b4e548bdde6d18356a9e3"
          }
        ],
        "columns": [
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2823ff27-31da-4e97-9f4a-2be614ad66df",
            "sourceColumn": "KFR_ET_Report[TourCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6142512c-9f81-4183-b87c-7d116303af63",
        "partitions": [
          {
            "name": "Dim_TourCode-f3bc5847-933e-4a04-9692-0bfa78ef5f16",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[TourCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_StartCountry",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f23f64870fb1440e9c62c7a7eef63389"
          }
        ],
        "columns": [
          {
            "name": "StartLocationCountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ff87f40e-2217-401b-9a69-a5958abe4970",
            "sourceColumn": "KFR_ET_Report[StartLocationCountryName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "53c22ab2-240a-4638-bbad-329321ac4b1b",
        "partitions": [
          {
            "name": "Dim_StartCountry-cf3d427e-aeb5-464c-939e-d9efd0e62d81",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[StartLocationCountryName])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_BudgetSeasonNum",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "75f95879a4a148b58c5798022b2af291"
          }
        ],
        "columns": [
          {
            "name": "BudgetSeasonNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "12d12c72-1160-4be5-a391-1c9c0a564543",
            "sourceColumn": "KFR_ET_Report[BudgetSeasonNum]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "cfbc8dc6-b5bd-484d-ba87-648677509752",
        "partitions": [
          {
            "name": "Dim_BudgetSeasonNum-b6773553-32ba-485d-9040-c35217dceec3",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[BudgetSeasonNum])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_CompTypeCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "502053552fc1483bb3b3fa913e2350b6"
          }
        ],
        "columns": [
          {
            "name": "CompTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e7aaafc3-e720-48e3-9638-308d320078d8",
            "sourceColumn": "KFR_ET_Report[CompTypeCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "bf7c61dc-3fc5-4705-8d1d-b55c7e920e5e",
        "partitions": [
          {
            "name": "Dim_CompTypeCode-5e34cf56-4c63-47e5-9b0e-ca62ddc80143",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[CompTypeCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_LookupCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "269691d1584440f48bc4484ae24f8279"
          }
        ],
        "columns": [
          {
            "name": "LookupCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1f9d14f7-1877-4da5-a661-4c53253ff597",
            "sourceColumn": "KFR_ET_Report[LookupCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6565d89d-8efc-4256-b5d4-86a2bfe87f20",
        "partitions": [
          {
            "name": "Dim_LookupCode-63642b19-e266-48fa-8220-db1149451ea4",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[LookupCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dim_CurrencyCode",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1d604d7517e74255bed54e3e94ec747e"
          }
        ],
        "columns": [
          {
            "name": "CurrencyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fa7d6cee-3bf5-401e-8b19-900b5cd12164",
            "sourceColumn": "KFR_ET_Report[CurrencyCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7009ce63-b9c7-4d8b-b45a-b2aaccdd3247",
        "partitions": [
          {
            "name": "Dim_CurrencyCode-18b481d9-d8f0-4995-822e-e1f0ecd3db37",
            "mode": "import",
            "source": {
              "expression": "DISTINCT(KFR_ET_Report[CurrencyCode])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Z_GroupSize_avg",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "453a43afc2a14a7f8e6fa0d3263140c6"
          }
        ],
        "columns": [
          {
            "name": "Z_GroupSize_avg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "decimal",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "#,0.00",
            "isNameInferred": false,
            "lineageTag": "7d7f094e-006b-4ab1-aed3-a6878d5510a7",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ae1b233c-e7f9-4f7d-a9b9-8e836a0072d9",
        "measures": [
          {
            "name": "Z_GroupSize_avg Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Z_GroupSize_avg'[Z_GroupSize_avg], 1)",
            "lineageTag": "a1c37d10-eee0-4764-b37b-670a7f26d175"
          },
          {
            "name": "GroupSize_avg_filter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "Var MyValue = CALCULATE([Z_GroupSize_avg Value], ALL(Z_GroupSize_avg))",
              "",
              "Var MyCurrent = SELECTEDVALUE(Z_GroupSize_avg[Z_GroupSize_avg])",
              "",
              "Var Calc = ",
              "    SWITCH(TRUE()",
              "        , MyCurrent > 20 && MyCurrent < 40, 1",
              "        // , MyCurrent > 0.8 * MyValue && MyCurrent < 1.2 * MyValue, 1",
              "        , 0",
              "    )",
              "",
              "Return Calc "
            ],
            "lineageTag": "0524b737-46ce-4b5d-a929-cc0447ab7bd7"
          }
        ],
        "partitions": [
          {
            "name": "Z_GroupSize_avg-0e3850d5-8e4b-49f1-8b71-7eb93aa9e2e6",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 50, 0.01)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Z_testing",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "be39145a01e6470699b265d8b2379c5b"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "72fd74d7-9854-4a57-bdb4-b40fef598c6c",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "92e2d51a-bf9b-46b5-904d-7a32b941fcce",
        "partitions": [
          {
            "name": "Z_testing-5a1ee7e8-72d3-4519-abf4-e2a90aced808",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 50, 0.01)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Other_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5abe24241d154c3d8325750484f60ffd"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0173f015-1145-470e-af0b-c0431e9489ea",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d84d6024-0dc4-45bc-9557-6a27aa507917",
        "measures": [
          {
            "name": "XX_LandCost_Diff_(1Dim)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//(1- (15008/134867)) * [LandCost_USD_1]",
              "",
              "//Scaling variables. ",
              "Var Pax1 =  CALCULATE([My_Travellers_1], ALL(KFR_ET_Report))",
              "Var DiffPax = CALCULATE([My_Travellers_diff], ALL(KFR_ET_Report))",
              "",
              "Var TravelScaling = 1 + [My_Travellers_diff]/[My_Travellers_1]",
              "",
              "//potentially change to busdiff instead of travellers. ",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        , KFR_ET_Report[BusinessUnit]",
              "        , KFR_ET_Report[TourRegionCode]",
              "        , KFR_ET_Report[TourCode]",
              "        // , KFR_ET_Report[IsPerGroup]",
              "        , \"USD\", [LandCost_USD_1]",
              "        , \"USD2\", [LandCost_USD_2]",
              "    )",
              "    , [USD2]  - TravelScaling * [USD]",
              ")",
              "",
              "Return Calc   "
            ],
            "lineageTag": "c2613b1e-f7a8-4d17-b705-494829542a1a"
          },
          {
            "name": "My_Travellers_diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[My_Travellers_2] - [My_Travellers_1]",
            "lineageTag": "6c601fdc-d07c-4538-ac29-4a714c32c9d0"
          },
          {
            "name": "LandCompare_TourCode",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var My_KFR = [Slicer_KFR_1]",
              "Var My_ComponentPeriod = [Slicer_Periods_1]",
              "Var My_FX = [Slicer_FX_1]",
              "",
              "Var My_KFR2 = [Slicer_KFR_2]",
              "Var My_ComponentPeriod2 = [Slicer_Periods_2]",
              "Var My_FX2 = [Slicer_FX_2]",
              "",
              "Var Calc3 = ",
              "SUMX(",
              "    ",
              "    SUMMARIZE(",
              "        // VALUES(KFR_ET_Report)",
              "        FILTER(KFR_ET_Report, ",
              "           ( KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX )",
              "            || ( KFR_ET_Report[My_KFR_Index] = My_KFR2 && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod2 && KFR_ET_Report[My_FX_Index] = My_FX2 )",
              "        )",
              "        ",
              "        // , KFR_ET_Report[BudgetSeasonNum]",
              "",
              "        , KFR_ET_TravelPattern[BusinessUnit]",
              "        , KFR_ET_TravelPattern[TourRegionCode]",
              "        , KFR_ET_TravelPattern[TourCode]",
              "",
              "        // , KFR_ET_Report[TourCode]",
              "        // , KFR_ET_Report[TourVersionCode]",
              "        // , KFR_ET_Report[Component]",
              "",
              "        , \"Land\", [LandCost_diff_USD]",
              "        , \"Sum1\", [My_Travellers_diff] * [Pax_1_sum]",
              "        , \"Sum2\", [My_Travellers_diff] * [Pax_2_sum]",
              "    )",
              "    // , [Land] - IF([Pax_1_sum] <> BLANK(), [Sum1], [Sum2])",
              "    , IF([Pax_1_sum] <> BLANK() && [Pax_2_sum] <> BLANK(), [Land] - [Sum1]) //, [Sum2])      ",
              ")",
              "",
              "",
              "Return Calc3"
            ],
            "lineageTag": "f6413bb3-8898-4e13-bb01-a680e163fa41"
          },
          {
            "name": "GroupCost_Compare",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var My_KFR = [Slicer_KFR_1]",
              "Var My_ComponentPeriod = [Slicer_Periods_1]",
              "Var My_FX = [Slicer_FX_1]",
              "",
              "Var My_KFR2 = [Slicer_KFR_2]",
              "Var My_ComponentPeriod2 = [Slicer_Periods_2]",
              "Var My_FX2 = [Slicer_FX_2]",
              "",
              "",
              "Var Calc3 = ",
              "SUMX(",
              "    ",
              "    SUMMARIZE(",
              "        // VALUES(KFR_ET_Report)",
              "        FILTER(KFR_ET_Report, ",
              "           ( KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX && KFR_ET_Report[IsPerGroup] = TRUE() )",
              "            || ( KFR_ET_Report[My_KFR_Index] = My_KFR2 && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod2 && KFR_ET_Report[My_FX_Index] = My_FX2 && KFR_ET_Report[IsPerGroup] = TRUE() ) ",
              "        )",
              "        ",
              "        , KFR_ET_Report[BudgetSeasonNum]",
              "        , KFR_ET_Report[TourCode]",
              "        , KFR_ET_Report[TourVersionCode]",
              "        , KFR_ET_Report[Component]",
              "",
              "        , \"Land\", [LandCost_diff_USD]",
              "        , \"Sum1\", [My_Travellers_diff] * [Pax_1_sum]",
              "        , \"Sum2\", [My_Travellers_diff] * [Pax_2_sum]",
              "    )",
              "    // , [Land] - IF([Pax_1_sum] <> BLANK(), [Sum1], [Sum2])",
              "    , IF([Pax_1_sum] <> BLANK() && [Pax_2_sum] <> BLANK(), [Land] - [Sum1]) //, [Sum2]) ",
              "            ",
              ")",
              "",
              "",
              "Return Calc3"
            ],
            "lineageTag": "a13c6a48-7d8c-4429-a96f-065e980234e5"
          },
          {
            "name": "Removed_Travellers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "// Var Opt1 = [Pax_1_sum]",
              "// Var Opt2 = [Pax_2_sum]",
              "",
              "// Var Calc = ",
              "//     SUMX(",
              "//         SUMMARIZE(FILTER(KFR_ET_Report, [Pax_1_sum] <> BLANK() && [Pax_2_sum] = BLANK())",
              "//             , KFR_ET_Report[TourCode]",
              "//             , KFR_ET_Report[BudgetSeasonNum]",
              "//             , \"USD\", [LandCost_diff_USD]",
              "//         )",
              "//         , [USD]",
              "//     )",
              "",
              "",
              "Var CalcPax = ",
              "SUMX(",
              "    SUMMARIZE(",
              "        //FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] in {[Slicer_KFR_2], [Slicer_KFR_1]})",
              "        // , KFR_ET_TravelPattern[My_KFR_Index]",
              "        FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = [Slicer_KFR_1] || KFR_ET_TravelPattern[My_KFR_Index] = [Slicer_KFR_2])",
              "        , KFR_ET_TravelPattern[FY_year]",
              "        // , KFR_ET_TravelPattern[TourRegionCode]",
              "        , KFR_ET_TravelPattern[BusinessUnit]",
              "        , KFR_ET_TravelPattern[TourCode]",
              "        // , KFR_ET_TravelPattern[BudgetSeasonNum]",
              "        // , KFR_ET_TravelPattern[TourVersionCode]",
              "        , \"USD\", [Removed_LandCost]",
              "        , \"Travellers\", [My_Travellers]",
              "    )",
              "    , IF([Removed_LandCost] <> BLANK(), [Travellers])",
              ")",
              "            ",
              "",
              "Return CalcPax"
            ],
            "lineageTag": "dad52d00-f361-4940-a483-edb2d37582e4"
          },
          {
            "name": "Removed_LandCost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var Opt1 = [Pax_1_sum]",
              "Var Opt2 = [Pax_2_sum]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        , KFR_ET_Report[BusinessUnit]",
              "        , KFR_ET_Report[TourCode]",
              "        // , KFR_ET_Report[TourVersionCode] //maybe maybe not. ",
              "        // , KFR_ET_Report[BudgetSeasonNum]",
              "        , \"USD\", [LandCost_diff_USD]",
              "        , \"Opt1\", [LandCost_USD_1]",
              "        , \"Opt2\", [LandCost_USD_2]",
              "    )",
              "    , IF( [Opt1] <> BLANK() && [Opt2] = BLANK(), [USD]) //LandCost in Option1 slicer but not in 2nd Option.",
              ")",
              "",
              "Return Calc "
            ],
            "lineageTag": "0be55498-49f2-4257-bb44-e55267e3f902"
          },
          {
            "name": "Removed_PaxPrice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Removed_LandCost], [Removed_Travellers])",
            "lineageTag": "e36a4726-5d4a-4e33-b0cb-dbf1ec7d3483"
          },
          {
            "name": "Added_Travellers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "",
              "Var CalcPax = ",
              "SUMX(",
              "    SUMMARIZE(",
              "        //FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] in {[Slicer_KFR_2], [Slicer_KFR_1]})",
              "        // , KFR_ET_TravelPattern[My_KFR_Index]",
              "        FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = [Slicer_KFR_1] || KFR_ET_TravelPattern[My_KFR_Index] = [Slicer_KFR_2])",
              "        , KFR_ET_TravelPattern[FY_year]",
              "        // , KFR_ET_TravelPattern[TourRegionCode]",
              "        , KFR_ET_TravelPattern[BusinessUnit]",
              "        , KFR_ET_TravelPattern[TourCode]",
              "        // , KFR_ET_TravelPattern[BudgetSeasonNum]",
              "        // , KFR_ET_TravelPattern[TourVersionCode]",
              "        , \"USD\", [Added_LandCost]",
              "        , \"Travellers\", [My_Travellers]",
              "    )",
              "    , IF([Added_LandCost] <> BLANK(), [Travellers])",
              ")",
              "            ",
              "",
              "Return CalcPax"
            ],
            "lineageTag": "24edbbb5-4ae3-4bb4-934b-3b2175c7f478"
          },
          {
            "name": "Added_LandCost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var Opt1 = [Pax_1_sum]",
              "Var Opt2 = [Pax_2_sum]",
              "",
              "// Var Calc = ",
              "// SUMX(",
              "//     SUMMARIZE(KFR_ET_Report",
              "//         , KFR_ET_Report[TourCode]",
              "//         // , KFR_ET_Report[TourVersionCode]",
              "//         , KFR_ET_Report[BudgetSeasonNum]",
              "//         , \"USD\", [LandCost_diff_USD]",
              "//         , \"Opt1\", [Pax_1_sum]",
              "//         , \"Opt2\", [Pax_2_sum]",
              "//     )",
              "//     , IF( [Opt1] = BLANK() && [Opt2] <> BLANK(), [USD]) //LandCost in Option2 slicer but not in 1st Option.",
              "// )",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        , KFR_ET_Report[BusinessUnit]",
              "        , KFR_ET_Report[TourCode]",
              "        // , KFR_ET_Report[TourVersionCode]",
              "        // , KFR_ET_Report[BudgetSeasonNum]",
              "        , \"USD\", [LandCost_diff_USD]",
              "        , \"Opt1\", [LandCost_USD_1]",
              "        , \"Opt2\", [LandCost_USD_2]",
              "    )",
              "    , IF( [Opt1] = BLANK() && [Opt2] <> BLANK(), [USD]) //LandCost in Option2 slicer but not in 1st Option.",
              ")",
              "",
              "",
              "Return Calc "
            ],
            "lineageTag": "d8322322-5346-4f7d-881e-0ecef0c1b841"
          },
          {
            "name": "Added_PaxPrice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Added_LandCost], [Added_Travellers])",
            "lineageTag": "ba6d7c21-d463-4f63-9c76-0476a12b123a"
          },
          {
            "name": "XX_PaxPrice_NotRemoved",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([LandCost_USD_1] + [Removed_LandCost], [My_Travellers_1] - [Removed_Travellers])",
            "lineageTag": "93632ff8-59ee-42c6-b521-aa9b92e68252"
          },
          {
            "name": "XX_PaxPrice_NotAdded",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE( [LandCost_USD_2] - [Added_LandCost], [My_Travellers_2] - [Added_Travellers])",
            "lineageTag": "0bd575c0-c2d6-4112-8166-ea3505bb19c3"
          },
          {
            "name": "Kept_LandCost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var Opt1 = [Pax_1_sum]",
              "Var Opt2 = [Pax_2_sum]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        , KFR_ET_Report[TourCode]",
              "        // , KFR_ET_Report[TourVersionCode] //maybe maybe not",
              "        // , KFR_ET_Report[BudgetSeasonNum]",
              "        , \"USD\", [LandCost_diff_USD]",
              "        , \"Opt1\", [Pax_1_sum]",
              "        , \"Opt2\", [Pax_2_sum]",
              "    )",
              "    , IF( [Opt1] <> BLANK() && [Opt2] <> BLANK(), [USD]) //LandCost in both.",
              ")",
              "",
              "Return Calc "
            ],
            "lineageTag": "ced8dc36-b609-43b0-849e-2b2869f8d415"
          },
          {
            "name": "Kept_LandCost1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//[LandCost_diff_USD] - [My_Travellers_diff] * [Pax_1_sum]",
              "",
              "Var Opt1 = [Pax_1_sum]",
              "Var Opt2 = [Pax_2_sum]",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        , KFR_ET_Report[TourCode]",
              "        , \"USD\", [LandCost_USD_1]",
              "        , \"Opt1\", [Pax_1_sum]",
              "        , \"Opt2\", [Pax_2_sum]",
              "    )",
              "    , IF( [Opt1] <> BLANK() && [Opt2] <> BLANK(), [USD]) //LandCost in both.",
              ")",
              "",
              "Return Calc "
            ],
            "lineageTag": "fe276753-8418-4693-bd7a-11bf6838b882"
          },
          {
            "name": "Diff_Land(%)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[LandCost_USD_2(%)] - [LandCost_USD_1(%)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "600f3f9e-0872-424a-a0aa-e703acf53b85"
          },
          {
            "name": "LandCost_USD_1(%)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [LandCost_USD_1]",
              "    , CALCULATE([LandCost_USD_1], ALLSELECTED('KFR_ET_Report'[CurrencyCode]))",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d1f77476-9bea-4020-adb4-f73e24d55c6f"
          },
          {
            "name": "LandCost_USD_2(%)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [LandCost_USD_2]",
              "    , CALCULATE([LandCost_USD_2], ALLSELECTED('KFR_ET_Report'[CurrencyCode]))",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b255f65d-3506-4877-9593-180ee0f0f615"
          },
          {
            "name": "XX_LandCurr",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[Diff_Land(%)] * [LandCost_USD_2]",
            "formatString": "#,0",
            "lineageTag": "b92922a7-ace5-4a5c-984a-cf0ca2f5d1cc"
          }
        ],
        "partitions": [
          {
            "name": "Other_Measures-d18e4445-fd6f-47f4-bcb2-365a12e15300",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Explanation",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2ada5274d80845fa80028d6a7e621a66"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7ddcdeb9-78fb-431f-9edc-7f8eedc95961",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "712cfcd3-e52d-44df-b9da-98d9e3a39882",
        "measures": [
          {
            "name": "Pax1_filled",
            "expression": [
              "",
              "",
              "    Switch(TRUE()",
              "        , ISBLANK([Pax_1]), [Pax_2_sum]",
              "        , [Pax_1_sum]",
              "    )",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "36ab6812-cfe5-46ab-9aca-bda3428a762d"
          },
          {
            "name": "Pax2_filled",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "    Switch(TRUE()",
              "        , ISBLANK([Pax_2]), [Pax_1_sum]",
              "        , [Pax_2_sum]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "5521ad94-a0ea-4b93-8347-7da9835df10e"
          },
          {
            "name": "Travellers1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        [My_Travellers_1],",
              "        CALCULATE([My_Travellers_1], ALLSELECTED(KFR_ET_Report))",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "42a6c8fb-ee29-44ec-a859-e5ecb2fa54e1"
          },
          {
            "name": "Travellers2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        [My_Travellers_2],",
              "        CALCULATE([My_Travellers_2], ALLSELECTED(KFR_ET_Report))",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5ae5e12a-32f8-44fd-8b50-ee10b587bae3"
          },
          {
            "name": "Travellers_adj",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "- ([Travellers2] - [Travellers1]) * CALCULATE([My_Travellers_2], ALLSELECTED(KFR_ET_Report))"
            ],
            "formatString": "#,0",
            "lineageTag": "526e44de-49bc-4144-84d3-b337e3106cbb"
          },
          {
            "name": "test",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        ,KFR_ET_Report[TourRegionCode]",
              "        // ,KFR_ET_Report[StartLocationCountryName]",
              "        // ,KFR_ET_Report[BudgetSeasonNum]",
              "        // ,KFR_ET_Report[TourTypeCode]",
              "        // ,KFR_ET_Report[TourCode]",
              "        // ,KFR_ET_Report[TourVersionCode]",
              "        , \"mycalc\", [Region_SimSwitch]",
              "    )",
              "    , [mycalc]",
              "    )"
            ],
            "lineageTag": "ba8dbada-2714-4491-bb00-dc3cee656f1a"
          },
          {
            "name": "testLevels",
            "expression": [
              "",
              "",
              "Switch(TRUE()",
              "    , ISFILTERED(KFR_ET_Report[TourRegionCode]), TRUE()",
              "    )",
              ""
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f00dd864-d287-414b-8a4d-dc74bee086b7"
          },
          {
            "name": "Country_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "22cfea5a-b9a6-4df0-9f6f-08a4139c5a33"
          },
          {
            "name": "Season_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "52e350f5-5a8d-40d0-a6b6-fe3220a9b611"
          },
          {
            "name": "TourType_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "e3d4e366-dc86-4b24-9bef-1b4c822d3ce3"
          },
          {
            "name": "TourCode_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "8e5dff8b-1391-4497-9580-a91dd6f9e5fc"
          },
          {
            "name": "TourVersion_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "5422818e-d12e-4736-8511-4be9e5c03e7e"
          },
          {
            "name": "BusEffect",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var MyCalc = ",
              "    [GroupCost_2] - DIVIDE([GroupCost_2], ( 1 / (1 + [BusDiff])))",
              "",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , \"mycalc\", [GroupCost_2] - DIVIDE([GroupCost_2], ( 1 / (1 + [BusDiff])))",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "dca23fca-eacf-49a9-b26f-65bce9b52a43"
          },
          {
            "name": "BusDiff",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "    SWITCH(TRUE()",
              "        ,  ISBLANK(Used_Measures[My_BusSize_1]) = FALSE() && ISBLANK(Used_Measures[My_BusSize_2]) = FALSE()",
              "            , DIVIDE([My_BusSize_2] , [My_BusSize_1]) - 1",
              "        , BLANK()",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c2370baa-83c7-4480-86a0-6a9badb8f413"
          },
          {
            "name": "NewSetUp",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "Explanation[Travellers_adj] + [My_Travellers_2]",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "f2975c60-e2e2-4cfd-9faa-a446641681c6"
          },
          {
            "name": "GroupCostDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              " Var Mycalc =",
              "    SWITCH(TRUE()",
              "        , ISBLANK([GroupCost_person_1]) = FALSE() && ISBLANK([GroupCost_person_2]) = FALSE()",
              "            , Explanation[NewSetUp] * ( [GroupCost_person_2] - [GroupCost_person_1] ) ",
              "        , BLANK()",
              "    )",
              "    ",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , \"mycalc\"",
              "                , SWITCH(TRUE()",
              "                    , ISBLANK([GroupCost_person_1]) = FALSE() && ISBLANK([GroupCost_person_2]) = FALSE()",
              "                        , Explanation[NewSetUp] * ( [GroupCost_person_2] - [GroupCost_person_1] ) ",
              "                    , BLANK()",
              "                )",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "f5e4ed48-5f84-4e0c-b6f3-7532e045bb34"
          },
          {
            "name": "PaxCostDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var MyCalc =",
              "    SWITCH(TRUE()",
              "        , ISBLANK([PaxCost_person_2]) = FALSE() && ISBLANK([PaxCost_person_1]) = FALSE()",
              "            , Explanation[NewSetUp] * ( [PaxCost_person_2] - [PaxCost_person_1] ) ",
              "        , BLANK()",
              "    )",
              "",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , \"mycalc\"",
              "                , SWITCH(TRUE()",
              "                     , ISBLANK([PaxCost_person_2]) = FALSE() && ISBLANK([PaxCost_person_1]) = FALSE()",
              "                        , Explanation[NewSetUp] * ( [PaxCost_person_2] - [PaxCost_person_1] ) ",
              "                    , BLANK()",
              "                )",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "375e3400-bc9b-4b93-b8ed-fb4557faa0d5"
          },
          {
            "name": "GroupCostTS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var MyCalc = [GroupCostDiff] - [BusEffect]",
              "",
              "Return MyCalc "
            ],
            "formatString": "#,0",
            "lineageTag": "1f4cdfdc-83de-4474-9329-af65b6eca7bd"
          },
          {
            "name": "PerPaxCostDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "[PaxCost_person_2] - [PaxCost_person_1]",
              "",
              "// Var MyCalc =",
              "//     SWITCH(TRUE()",
              "//         , ISBLANK([PaxCost_person_2]) = FALSE() && ISBLANK([PaxCost_person_1]) = FALSE()",
              "//             , ( [PaxCost_person_2] - [PaxCost_person_1] ) ",
              "//         , BLANK()",
              "//     )",
              "",
              "// Return MyCalc ",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "41d432db-9470-4db3-94db-740b80813fb5"
          },
          {
            "name": "PerGroupCostDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "[GroupCost_person_2] - [GroupCost_person_1]",
              "",
              "//  Var Mycalc =",
              "//     SWITCH(TRUE()",
              "//         , ISBLANK([GroupCost_person_1]) = FALSE() && ISBLANK([GroupCost_person_2]) = FALSE()",
              "//             , ( [GroupCost_person_2] - [GroupCost_person_1] ) ",
              "//         , BLANK()",
              "//     )",
              "",
              "// Return Mycalc "
            ],
            "formatString": "#,0",
            "lineageTag": "7d3d1419-a023-499f-85dd-2cc193b362cf"
          },
          {
            "name": "Topx_GroupCost",
            "expression": [
              "",
              "",
              "IF(",
              "    RANKX(ALLSELECTED(KFR_ET_Report), ABS([PerGroupCostDiff]), , DESC, Dense ) <= 10",
              "    , [PerGroupCostDiff]",
              "    , BLANK()",
              ")",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "186a075a-faef-4d43-ac14-3730da1b2ae6"
          },
          {
            "name": "GroupCostDiff_changeTS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//  Var Mycalc =",
              "//     SWITCH(TRUE()",
              "//         , ISBLANK([GroupCost_person_1]) = FALSE() && ISBLANK([GroupCost_person_2]) = FALSE()",
              "//             , Explanation[NewSetUp] * ( [GroupCost_person_2] - [GroupCost_person_1] ) ",
              "//         , BLANK()",
              "//     )",
              "    ",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Quantity]",
              "            ",
              "            , \"mycalc\", IF( ISBLANK([GroupCost_person_1]) || ISBLANK([GroupCost_person_2]) , [GroupCost_person_2] - [GroupCost_person_1])",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "",
              "// //Returning total or calculation.",
              "// Var Calc3 = ",
              "//     SWITCH(TRUE()",
              "//         , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "//         , Calc2",
              "//     )",
              "",
              "Return Calc2 "
            ],
            "lineageTag": "9feaeef0-cd59-4306-b17b-13c70aa956f6"
          },
          {
            "name": "GroupCostDiff_changeTS_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Quantity]",
              "            ",
              "            , \"mycalc\", IF( ISBLANK([GroupCost_person_1]) || ISBLANK([GroupCost_person_2]) , [GroupCost_person_2] - [GroupCost_person_1]) //* [NewSetUp] //[My_Travellers_2] ",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "Return Calc2 "
            ],
            "formatString": "#,0",
            "lineageTag": "6cd6aa45-ba77-4ea1-8394-8c3d771d7894"
          },
          {
            "name": "PaxCostDiff_changeTS_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[StartLocationCountryName]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Quantity]",
              "            ",
              "            , \"mycalc\", IF( ISBLANK([PaxCost_person_1]) || ISBLANK([PaxCost_person_2]) , [PaxCost_person_2] - [PaxCost_person_1]) //* [NewSetUp] //[My_Travellers_2] ",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "    ",
              "",
              "Return Calc2 "
            ],
            "formatString": "#,0",
            "lineageTag": "3d26c2d4-1735-4615-bdd3-ddaa2add436a"
          },
          {
            "name": "PaxCostDiff__same_volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        ,KFR_ET_Report[TourRegionCode]",
              "        ,KFR_ET_Report[TourTypeCode]",
              "        ,KFR_ET_Report[StartLocationCountryName]",
              "        ,KFR_ET_Report[BudgetSeasonNum]",
              "        ,KFR_ET_Report[TourCode]",
              "        ,KFR_ET_Report[TourVersionCode]",
              "        , \"mycalc\", [PaxCostDiff_same] * Used_Measures[My_Travellers_2]",
              "    )",
              "    , [mycalc]",
              ")",
              "",
              "Return Calc "
            ],
            "lineageTag": "0d3c401c-709a-4093-a4f2-a793b137533f"
          },
          {
            "name": "PaxCostDiff_same",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "IF( ",
              "   ( ISBLANK([PaxCost_person_1])= FALSE() && ISBLANK([PaxCost_person_2])= FALSE() )",
              "        , ([PaxCost_person_2] - [PaxCost_person_1]) ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "04cd0bcf-9459-4414-a2d2-401844d298b2"
          },
          {
            "name": "CostDiff_same",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "IF( ",
              "   ( ISBLANK([Pax_1_sum])= FALSE() && ISBLANK([Pax_2_sum])= FALSE() )",
              "        , ([Pax_2_sum] - [Pax_1_sum]) ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "b8e88f13-b7d0-450d-9981-0f5df4342aea"
          },
          {
            "name": "CostDiff_same_volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "",
              "Var Calc = ",
              "SUMX(",
              "    SUMMARIZE(KFR_ET_Report",
              "        ,KFR_ET_Report[TourRegionCode]",
              "        ,KFR_ET_Report[TourTypeCode]",
              "        ,KFR_ET_Report[StartLocationCountryName]",
              "        ,KFR_ET_Report[BudgetSeasonNum]",
              "        ,KFR_ET_Report[TourCode]",
              "        ,KFR_ET_Report[TourVersionCode]",
              "        , \"mycalc\", [CostDiff_same] * Used_Measures[My_Travellers_2]",
              "    )",
              "    , [mycalc]",
              ")",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "130f3078-4b94-46ca-ba20-a3bfba8103f2"
          },
          {
            "name": "Region_Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Simulation calc",
              "Var MyCalc = [Travellers_adj] * [Pax2_filled]",
              "",
              "//Total number",
              "Var Calc2 = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , \"mycalc\", [Travellers_adj] * [Pax2_filled]",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "//Returning total or calculation.",
              "Var Calc3 = ",
              "    SWITCH(TRUE()",
              "        , ISFILTERED(KFR_ET_Report[TourRegionCode]), MyCalc",
              "        , Calc2",
              "    )",
              "",
              "Return Calc3"
            ],
            "formatString": "#,0",
            "lineageTag": "56cf7f53-4bb1-4733-8a81-3654241c963a"
          },
          {
            "name": "ChangeTS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Total number",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[LookupCode]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Quantity]",
              "            ",
              "            , \"mycalc\"",
              "                , IF( ISBLANK([Pax_1]) || ISBLANK([Pax_2])",
              "                    , [Pax_2_sum] - [Pax_1_sum], BLANK() ",
              "                ) ",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "5f811af5-6c8b-485b-85c8-2aea95ab7bdd"
          },
          {
            "name": "ChangeTS_Volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "//Total number",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , \"mycalc\", [ChangeTS] * [My_Travellers_2]  ",
              "        )",
              "        , [mycalc]",
              "    )",
              "",
              "Return Calc "
            ],
            "formatString": "#,0",
            "lineageTag": "0549f60d-ed6f-49e2-aee4-45fbdefa2818"
          },
          {
            "name": "ChangeTourCodesTS_diff",
            "expression": [
              "",
              "",
              "//Checking if TourCode, Version, season exists in both. ",
              "Var Calc = ",
              "    SUMX(",
              "        SUMMARIZE(KFR_ET_Report",
              "            , KFR_ET_Report[TourRegionCode]",
              "            , KFR_ET_Report[TourTypeCode]",
              "            , KFR_ET_Report[TourCode]",
              "            , KFR_ET_Report[TourVersionCode]",
              "            , KFR_ET_Report[BudgetSeasonNum]",
              "            , \"mycalc\", IF( ISBLANK([My_Travellers_1]) = FALSE() && ISBLANK([My_Travellers_2]) = FALSE() , 1) ",
              "        )",
              "        , [mycalc]",
              "    )",
              " ",
              "Return Calc "
            ],
            "formatString": "0",
            "lineageTag": "1408894b-6bf1-41f5-9d00-489a91fc8033"
          }
        ],
        "partitions": [
          {
            "name": "Explanation-e07ac0e6-8a10-4f99-9bc7-ff96b2448221",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Z_FX_usdeur",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "70ca953b7416470488a1f00d3fd0633f"
          }
        ],
        "columns": [
          {
            "name": "FX_eurusd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "ebf4d412-0eca-428e-9b3e-b51b0f863ab7",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7a429f44-0f2c-420d-851f-f3ba95c74c35",
        "measures": [
          {
            "name": "FX_usdeur Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "SELECTEDVALUE('Z_FX_usdeur'[FX_eurusd], \"\")",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d7687fee-5248-43e7-bb1e-f1f8a2c0bc3c"
          },
          {
            "name": "Max_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "MAX(Z_FX_usdeur[FX_eurusd])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2b495fa0-d5ea-404f-9989-39a14e1d912b"
          },
          {
            "name": "Min_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "MIN(Z_FX_usdeur[FX_eurusd])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "34ba43d3-ffe6-4271-a1cb-4ca0d3d11951"
          },
          {
            "name": "Pax_1_sim_MinEUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "",
              "//including group size simulation.",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyTable = ",
              "",
              "ADDCOLUMNS(",
              "    SUMMARIZE(",
              "        FILTER(KFR_ET_Report, KFR_ET_Report[My_KFR_Index] = My_KFR && KFR_ET_Report[My_Periods_Index] = My_ComponentPeriod && KFR_ET_Report[My_FX_Index] = My_FX",
              "        )",
              "",
              "            // , KFR_ET_Report[Comp_key_ext]",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "",
              "            , \"NewUSD\", ",
              "",
              "                IF(KFR_ET_Report[Curr_Index] <> [Curr1] && KFR_ET_Report[Curr_Index] <> [Curr2] //&& KFR_ET_Report[Curr_Index] <> [Curr3]",
              "                    , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate]",
              "",
              "                    , Switch(TRUE()",
              "                        , KFR_ET_Report[Curr_Index] = [Curr1]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr1_shift]) ",
              "                        , KFR_ET_Report[Curr_Index] = [Curr2]",
              "                            , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr2_shift]) ",
              "                        // , KFR_ET_Report[Curr_Index] = [Curr3]",
              "                        //     , KFR_ET_Report[Quantity] * KFR_ET_Report[LocalAmount] * KFR_ET_Report[Rate] * (1 + [Curr3_shift]) ",
              "                    )",
              "                )",
              "",
              "    )",
              "",
              "    , \"NewUSD2\", ",
              "        if(KFR_ET_Report[Combination_Index] <> [Comb1] && KFR_ET_Report[Combination_Index] <> [Comb2] ",
              "            , [NewUSD]",
              "",
              "            , SWITCH(TRUE()",
              "                , KFR_ET_Report[Combination_Index] = [Comb1]",
              "                    , [NewUSD] * (1 + [Comb1_shift])",
              "                , KFR_ET_Report[Combination_Index] = [Comb2]",
              "                    , [NewUSD] * (1 + [Comb2_shift])",
              "",
              "                //add more here.",
              "            )",
              "        )",
              ")",
              "",
              "",
              "//Currency Min/Max scenario for USDEUR. ",
              "Var MyTable2 = ",
              "    SUMMARIZE(MyTable ",
              "            ,KFR_ET_Report[Component]",
              "            , KFR_ET_Report[CompTypeCode]",
              "            , KFR_ET_Report[Combination_Index] //index for region and comptypecode.",
              "            , KFR_ET_Report[CompStartDay]",
              "            , KFR_ET_Report[Sequence]",
              "            , KFR_ET_Report[Quantity]",
              "            , KFR_ET_Report[IsPerGroup]",
              "            , KFR_ET_Report[CurrencyCode]",
              "            , KFR_ET_Report[Curr_Index]",
              "            , KFR_ET_Report[Rate]",
              "            , KFR_ET_Report[LocalAmount]",
              "            , KFR_ET_Report[LocalTotal_USD]",
              "            , KFR_ET_Report[LocalTotal_USD_group]",
              "            ",
              "            , [NewUSD2]",
              "            ",
              "            , \"NewUSD3\", IF(KFR_ET_Report[CurrencyCode] = \"EUR\", [NewUSD2] * (1 - [Min_EUR]/100) , [NewUSD2]) ",
              "    )",
              "",
              "",
              "Var USD_calc_group = ",
              "            DIVIDE(",
              "                SUMX(FILTER(MyTable2, [IsPerGroup] = TRUE()), [NewUSD3]) * [TP_BusCount_1]",
              "                , ([TP_Travellers_1] * [GroupSize_move])",
              "            )",
              "",
              "",
              "Var USD_calc_pax = SUMX(FILTER(MyTable2, [IsPerGroup] = FALSE()), [NewUSD3]) ",
              "",
              "Var Calc = USD_calc_group + USD_calc_pax",
              "",
              "Return Calc      "
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "504fb8b7-0f1b-43ce-b5cc-7d1b66b2ee87"
          },
          {
            "name": "Pax_1_sum_sim_MinEUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "Var My_KFR = KFR_ET_DIM_Slicer1[Slicer_KFR_1]",
              "Var My_ComponentPeriod = KFR_ET_DIM_Slicer1[Slicer_Periods_1]",
              "Var My_FX = KFR_ET_DIM_Slicer1[Slicer_FX_1]",
              "",
              "Var MyYear = VALUE(\"20\" & MID(SELECTEDVALUE(KFR_ET_DIM_Slicer1[Period]),2,2))",
              "",
              "",
              "Var Calc = ",
              "    DIVIDE(",
              "        SUMX(FILTER(KFR_ET_TravelPattern, KFR_ET_TravelPattern[My_KFR_Index] = My_KFR && KFR_ET_TravelPattern[FY_year] = MyYear)",
              "        , [Pax_1_sim_MinEUR] * [TP_Travellers_1]",
              "        )",
              "        , [TP_Travellers_1] //My Filtered volume. ",
              "    )",
              "",
              "Return Calc"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8266fae7-6c61-4f9a-80f0-947aa1caf6d7"
          },
          {
            "name": "Pax_CurrDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Pax_1_sum_sim_MinEUR] - My_Measure[Pax_1_sum_sim]",
            "lineageTag": "41ac8967-948c-49b1-b9c1-7ff227c91fec"
          },
          {
            "name": "EUR_part",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "CALCULATE(My_Measure[Pax_1_sum_sim], KFR_ET_Report[CurrencyCode] = \"EUR\")",
              "",
              "",
              "// Var Calc = ",
              "//     GROUPBY(KFR_ET_Report ",
              "//         , KFR_ET_Report[ProductMarketCode]",
              "//         , KFR_ET_Report[CurrencyCode]",
              "//         , \"PaxSim\", [Pax_1_sum_sim]",
              "//     )"
            ],
            "lineageTag": "6c61edc9-cde7-4cc0-8c70-4cb6c33fed3d"
          },
          {
            "name": "Eur_effect",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "",
              "    Z_FX_usdeur[EUR_part] * (1- [Min_EUR]/100)",
              "     - Z_FX_usdeur[EUR_part]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b170ac41-70fc-4d37-b049-f02706236501"
          }
        ],
        "partitions": [
          {
            "name": "Z_FX_usdeur-accf9379-2143-4e3a-9051-5e9d70b0c639",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(CURRENCY(-10), CURRENCY(10), CURRENCY(0.01))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "KFR_ET_TravelPattern",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e55e473a-ddb4-4004-aeff-5f888a0bed0c",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "KFR_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fe7947cd-d86b-4bee-9de2-b549ad3d82f1",
            "sourceColumn": "KFR_DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4b9ff6d5-2466-4975-9d40-5891325a8acb"
                },
                "isDefault": true,
                "relationship": "000191c8-2e4e-4195-bad8-c1e0aad0c080"
              }
            ]
          },
          {
            "name": "ProductMarketCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62c89be8-dc5f-472f-b9f6-1688bd694842",
            "sourceColumn": "ProductMarketCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff48176f-23ed-4f1e-a59a-e85489dc6d72",
            "sourceColumn": "TourTypeCode",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11cae786-ebee-4814-8de1-36e59bb13d82",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "FYCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02f63c79-876f-445f-95f7-95e376357457",
            "sourceColumn": "FYCODE",
            "summarizeBy": "none"
          },
          {
            "name": "FY_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a7700bb2-2b9e-46a5-9ae1-6d0e4e06453b",
            "sourceColumn": "FY_YEAR",
            "summarizeBy": "sum"
          },
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "107dee28-ad43-4eb8-9a6f-4d695cd8aa04",
            "sourceColumn": "TourRegionCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8a60851-e517-4932-b242-f8251684b112",
            "sourceColumn": "TourCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourVersionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4eb0a5be-bb87-432f-b469-62910af3f3ac",
            "sourceColumn": "TourVersionCode",
            "summarizeBy": "sum"
          },
          {
            "name": "TourDuration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0432cdb6-b442-44a3-bfe9-3ea832692acd",
            "sourceColumn": "TourDuration",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURSTARTLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b46297f6-e31b-4acc-9514-82c70034b295",
            "sourceColumn": "TOURSTARTLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "TOURENDLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a661acb-4a9d-4244-af2b-2bf1fd27022d",
            "sourceColumn": "TOURENDLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "TRAVELLERS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a7e20f1-604d-4660-963f-72abc96c9788",
            "sourceColumn": "TRAVELLERS",
            "summarizeBy": "sum"
          },
          {
            "name": "PAYINGPAX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "228cd7d0-fa4d-40f7-a869-63bdb93f0d38",
            "sourceColumn": "PAYINGPAX",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "308853e1-3a82-4fc6-bb86-9bdd86a8dc81",
            "sourceColumn": "BUSCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSEXTCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c9bb96e-1c33-42c8-ab03-37d79f695af0",
            "sourceColumn": "BUSEXTCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetSeasonNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06b8e77b-a782-4cee-866d-996cff1bb213",
            "sourceColumn": "BudgetSeasonNum",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_key_ext",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4f83a8b-93ab-45ce-befb-e511b4df7ae6",
            "sourceColumn": "TP_key_ext",
            "summarizeBy": "none"
          },
          {
            "name": "TP_key_adj",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce47134c-0c60-446d-939c-1090533af45c",
            "sourceColumn": "TP_key_adj",
            "summarizeBy": "none"
          },
          {
            "name": "TP_KEY_EXT_UNIQUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04a5e1d8-2304-4ec7-8fa0-e0ef3eeb3884",
            "sourceColumn": "TP_KEY_EXT_UNIQUE",
            "summarizeBy": "none"
          },
          {
            "name": "PERFECT_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a0a72b3c-eef8-4f2e-92b5-8107d195b003",
            "sourceColumn": "PERFECT_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_KFR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "973a86fe-8245-4f6c-8faf-642e7521fbd5",
            "sourceColumn": "MY_KFR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_FILTER_KEY_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "617a5552-d2c7-4c77-8846-a987b09c0204",
            "sourceColumn": "MY_FILTER_KEY_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e05c91b8-a51f-487c-9b01-9d02ef9da1ee",
        "partitions": [
          {
            "name": "KFR_ET_TravelPattern",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_TRAVELPATTERN_V\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"BUSINESSUNIT\", \"BusinessUnit\"}, {\"PRODUCTMARKETCODE\", \"ProductMarketCode\"}, {\"TOURCODE\", \"TourCode\"}, {\"TOURDURATION\", \"TourDuration\"}, {\"TOURREGIONCODE\", \"TourRegionCode\"}, {\"TOURVERSIONCODE\", \"TourVersionCode\"}, {\"TP_DESC\", \"TP_Desc\"}, {\"TOURTYPECODE\", \"TourTypeCode\"}, {\"BUDGETSEASONNUM\", \"BudgetSeasonNum\"}, {\"TP_KEY_EXT\", \"TP_key_ext\"}, {\"TP_KEY_ADJ\", \"TP_key_adj\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4b9ff6d5-2466-4975-9d40-5891325a8acb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "48fdd2ee-87a1-4c26-ab63-9cc9c96ba7ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2eae5d3d-6f7a-4cf6-a276-aa5fbefa6332",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1ced7674-feab-466d-95e5-2934dc55ab6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6adf3f61-c4bc-46ce-8520-199504085676",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "873f3ac7-dfa8-41f1-9661-9b585b8ca3f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "eee024bc-bb87-48a1-8c77-83c05d3c430d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "93e384a9-d511-4eca-ab0b-83cee79760c1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4be210ae-07fe-4c67-9e7b-6ddd705a727e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "601c30d5-7806-4893-96f2-f33a3301a106",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a90b7935-d9d4-43b5-8e01-4548195967b0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bc28c7e6-495d-4ead-b54d-4a89b13b722a",
                "ordinal": 3
              }
            ],
            "lineageTag": "693c50fb-7fde-4d93-a4bc-66e79d0f4bf1"
          }
        ],
        "isHidden": true,
        "lineageTag": "87e8e63b-7873-473d-9f13-bcd65365ee60",
        "partitions": [
          {
            "name": "LocalDateTable_4b9ff6d5-2466-4975-9d40-5891325a8acb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_TravelPattern'[KFR_DATE])), 1, 1), Date(Year(MAX('KFR_ET_TravelPattern'[KFR_DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "KFR_ET_Report",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96fd9331-c3ec-4d55-9a62-d52c93bd70dc",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "ProductMarketCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b41ff83-58c6-4ecc-a374-859a09abf70d",
            "sourceColumn": "ProductMarketCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a617a35-a2b7-4b84-af4f-2cf5a6a025a4",
            "sourceColumn": "TourTypeCode",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c786ce53-9fad-48fb-ae32-21e88305412c",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "FY_YEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "98c84cd8-b240-4d04-969d-5694fe9a0b6e",
            "sourceColumn": "FY_YEAR",
            "summarizeBy": "sum"
          },
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fac3a521-d0d1-482e-82f6-97ed087b8317",
            "sourceColumn": "TourRegionCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d163cb1f-d1b0-4165-b430-367c0841e821",
            "sourceColumn": "TourCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourVersionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5325d91e-b2d2-4b2d-a0bb-d0ed42d8d0e4",
            "sourceColumn": "TourVersionCode",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURDURATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e80ff0cd-321d-464b-87d9-12deb02bd14c",
            "sourceColumn": "TOURDURATION",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURSTARTLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "203ab555-0452-4636-9798-0c277d4929ff",
            "sourceColumn": "TOURSTARTLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "TOURENDLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d83a0ff-f1cd-4950-a582-c39859f1c249",
            "sourceColumn": "TOURENDLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "SALESTOURID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27ed735e-7470-4833-afc2-41d5933a8b2c",
            "sourceColumn": "SALESTOURID",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTUREDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0ad3dfd8-a102-4c2f-8ed9-b7f149334726",
            "sourceColumn": "DEPARTUREDATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_af4f99d0-a7e4-4bf4-a3ca-4429e1d7f0c2"
                },
                "isDefault": true,
                "relationship": "712cd2f1-658a-46cd-8c65-a2ebcab04596"
              }
            ]
          },
          {
            "name": "TRAVELLERS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8fa72f8c-7f63-48a9-a0c8-fbca3eebf1b5",
            "sourceColumn": "TRAVELLERS",
            "summarizeBy": "sum"
          },
          {
            "name": "PAYINGPAX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a965bf51-9663-41c9-b235-34c8a86e1d14",
            "sourceColumn": "PAYINGPAX",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2c004f65-b3a6-4c89-beb1-da6bf667a723",
            "sourceColumn": "BUSCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSEXTCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef96da00-7af1-4b93-903c-57c85a770b24",
            "sourceColumn": "BUSEXTCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetSeasonNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "004c33e8-f5fb-427a-8e13-f7932ce256e2",
            "sourceColumn": "BudgetSeasonNum",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_key_ext",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df9eaa7b-8318-4c86-b635-1cb8c6cc835d",
            "sourceColumn": "TP_key_ext",
            "summarizeBy": "none"
          },
          {
            "name": "TP_key_adj",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b866ea3f-e09c-4cf7-9f71-f2a4c2cde63c",
            "sourceColumn": "TP_key_adj",
            "summarizeBy": "none"
          },
          {
            "name": "TP_KEY_EXT_UNIQUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc506926-14d4-4bfd-8fff-b0b98436d7ab",
            "sourceColumn": "TP_KEY_EXT_UNIQUE",
            "summarizeBy": "none"
          },
          {
            "name": "PERFECT_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cfe1e6f-64d7-477c-afe9-cc64d2005e50",
            "sourceColumn": "PERFECT_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "SNAPSHOTDATE_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "480712dd-ef4b-4db6-a706-3aadeee7fcbd",
            "sourceColumn": "SNAPSHOTDATE_KEY",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6e22cbda-09e7-42ef-8249-c709e1047e4b",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e2060e6c-ad33-450c-aaf3-64a78030d959"
                },
                "isDefault": true,
                "relationship": "dd644ebb-c5d1-46af-bf1d-773b8cccbfd9"
              }
            ]
          },
          {
            "name": "COMP_KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "008e9389-688e-497b-8a73-c4f07f309246",
            "sourceColumn": "COMP_KEY",
            "summarizeBy": "none"
          },
          {
            "name": "COMPONENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "280769f3-31d4-4027-afd7-e98dcd89b445",
            "sourceColumn": "COMPONENT",
            "summarizeBy": "none"
          },
          {
            "name": "TOURYEARCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e7c7273-605d-440b-a642-313ad322e286",
            "sourceColumn": "TOURYEARCODE",
            "summarizeBy": "none"
          },
          {
            "name": "TOURYEARNUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9bedc65b-9c06-47d9-9ebb-bada120242bc",
            "sourceColumn": "TOURYEARNUM",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f889574a-bcd4-4745-a6cf-c0a989d04fc7",
            "sourceColumn": "TOURNAME",
            "summarizeBy": "none"
          },
          {
            "name": "StartLocationCountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52c86434-3085-43a6-b0d3-20eeba9a64a3",
            "sourceColumn": "StartLocationCountryName",
            "summarizeBy": "none"
          },
          {
            "name": "ENDLOCATIONCOUNTRYNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbfd12a0-5657-4806-bb72-fdf3362fec4c",
            "sourceColumn": "ENDLOCATIONCOUNTRYNAME",
            "summarizeBy": "none"
          },
          {
            "name": "STARTLOCATIONCITYNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fb94340-4518-4d84-9bba-2fea3a3e9fdc",
            "sourceColumn": "STARTLOCATIONCITYNAME",
            "summarizeBy": "none"
          },
          {
            "name": "ENDLOCATIONCITYNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bd1b43d-4d26-40a1-ae5e-ab3d6bcc7116",
            "sourceColumn": "ENDLOCATIONCITYNAME",
            "summarizeBy": "none"
          },
          {
            "name": "SEASON",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6667cc4a-189e-45df-95e9-aec4bfcc0379",
            "sourceColumn": "SEASON",
            "summarizeBy": "none"
          },
          {
            "name": "CompTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85e980d0-8e92-4c6d-8ba8-b76362d12fce",
            "sourceColumn": "CompTypeCode",
            "summarizeBy": "none"
          },
          {
            "name": "LookupCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ef757f7-e215-4cb5-a8d3-7e73cd8b6e06",
            "sourceColumn": "LookupCode",
            "summarizeBy": "none"
          },
          {
            "name": "COMPSPEC_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63d5364e-f33a-499b-b5a2-de1b85ce5d06",
            "sourceColumn": "COMPSPEC_ID",
            "summarizeBy": "count"
          },
          {
            "name": "COMPSTARTDAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5789e2f1-cd87-4f50-ba35-742b27f5e950",
            "sourceColumn": "COMPSTARTDAY",
            "summarizeBy": "sum"
          },
          {
            "name": "SEQUENCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aaf1e07f-8064-4a08-bfdd-2094c6823c9b",
            "sourceColumn": "SEQUENCE",
            "summarizeBy": "sum"
          },
          {
            "name": "DURATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c34c6e07-be6c-4f96-8572-54832885fd50",
            "sourceColumn": "DURATION",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b5cc9f1-0a6a-4b56-949b-c7c74ad90914",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "IsOptional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "957badc0-5afb-4dea-b6ea-0660eb28a58d",
            "sourceColumn": "IsOptional",
            "summarizeBy": "none"
          },
          {
            "name": "IsPerGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8cccb050-ce8f-4edd-97e1-db1bf27858bb",
            "sourceColumn": "IsPerGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "927bf64f-a37c-468a-ba4b-64230001a522",
            "sourceColumn": "CurrencyCode",
            "summarizeBy": "none"
          },
          {
            "name": "LOCALAMOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2499c59-2bda-48a0-a043-12d977114284",
            "sourceColumn": "LOCALAMOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe242b7f-487f-4122-ab04-a26f448cf178",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "PERIODINDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a879b496-2914-4016-9113-2767b3b22f62",
            "sourceColumn": "PERIODINDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "CHOSENPERIOD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7418831-3d37-4965-9cb3-91668520ee93",
            "sourceColumn": "CHOSENPERIOD",
            "summarizeBy": "none"
          },
          {
            "name": "FILLEDBUDGETFLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f1c1c5b-d07a-4cee-bc61-c3b391635195",
            "sourceColumn": "FILLEDBUDGETFLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "LOCALTOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2f5de2a8-7b7e-4969-8ed4-0a560034ee9c",
            "sourceColumn": "LOCALTOTAL",
            "summarizeBy": "sum"
          },
          {
            "name": "LOCALTOTAL_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcaf2623-28f6-4f15-8122-16d3306e8e3a",
            "sourceColumn": "LOCALTOTAL_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "LOCALTOTAL_USD_GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b0eb748-a587-4ebd-a56c-8ec5da4bfd0f",
            "sourceColumn": "LOCALTOTAL_USD_GROUP",
            "summarizeBy": "sum"
          },
          {
            "name": "USD_COST_PRECALC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c316d1e4-aefa-4dc1-8b76-aa71b9a9a0c2",
            "sourceColumn": "USD_COST_PRECALC",
            "summarizeBy": "sum"
          },
          {
            "name": "FX_period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce64e029-d707-4cc9-8dcf-312afb473abb",
            "sourceColumn": "FX_period",
            "summarizeBy": "none"
          },
          {
            "name": "RATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8e92530-fc55-40f4-8e33-9b6c5f1ca49b",
            "sourceColumn": "RATE",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_KFR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "84412a29-44b9-40f1-887d-c7397e0d2020",
            "sourceColumn": "MY_KFR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_PERIODS_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b41f440-8dd7-4c3a-a502-3cd95e178d9a",
            "sourceColumn": "MY_PERIODS_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_FX_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f39d06e6-8700-4e30-bebc-f76fced98a99",
            "sourceColumn": "MY_FX_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_FILTER_KEY_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "547dd5ec-38d4-41bc-893d-277eaced66e4",
            "sourceColumn": "MY_FILTER_KEY_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "CURR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1b451a6-2ab7-4e62-94b5-63b63921eea8",
            "sourceColumn": "CURR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "COMBINATION_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3bcedbbc-ddc7-44df-beb0-02c5af455a51",
            "sourceColumn": "COMBINATION_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "40db9a40-4698-4742-bf49-7c6443e7d0c4",
        "partitions": [
          {
            "name": "KFR_ET_Report",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_REPORT_V\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"BUSINESSUNIT\", \"BusinessUnit\"}, {\"COMPTYPECODE\", \"CompTypeCode\"}, {\"LOOKUPCODE\", \"LookupCode\"}, {\"ISOPTIONAL\", \"IsOptional\"}, {\"ISPERGROUP\", \"IsPerGroup\"}, {\"TP_DESC\", \"TP_Desc\"}, {\"DATE\", \"Date\"}, {\"PERIOD\", \"Period\"}, {\"FX_PERIOD\", \"FX_period\"}, {\"PRODUCTMARKETCODE\", \"ProductMarketCode\"}, {\"TOURREGIONCODE\", \"TourRegionCode\"}, {\"TOURTYPECODE\", \"TourTypeCode\"}, {\"TOURCODE\", \"TourCode\"}, {\"TOURVERSIONCODE\", \"TourVersionCode\"}, {\"BUDGETSEASONNUM\", \"BudgetSeasonNum\"}, {\"STARTLOCATIONCOUNTRYNAME\", \"StartLocationCountryName\"}, {\"CURRENCYCODE\", \"CurrencyCode\"}, {\"TP_KEY_EXT\", \"TP_key_ext\"}, {\"TP_KEY_ADJ\", \"TP_key_adj\"}, {\"QUANTITY\", \"Quantity\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_af4f99d0-a7e4-4bf4-a3ca-4429e1d7f0c2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8c244db1-cca9-46c4-8ead-eb4e2c1950bf",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f25c7447-42d5-4530-b4be-27d78170a950",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "797b4fd7-548a-4bb5-9cb4-3fa4eeb5b502",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a986c1a3-17bf-4129-bf36-9e52192b4c9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "60203f9f-bc1f-4feb-8bed-d74e5bd8782c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1b98d829-165b-4e51-a109-e1e3801c8da6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0d880b4b-5552-4053-acc3-22f2b5ac08ff",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1b3eb958-a786-45d4-a8f0-e46a44844419",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "246e3998-00b0-4c92-9b9e-f15db9c40418",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2d953c8c-6efd-419f-afb3-0f4cc2b7f02d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b8c2796d-ff79-4747-b62d-3ed628990057",
                "ordinal": 3
              }
            ],
            "lineageTag": "2f668c47-94fd-4ff7-8a62-4abb4563bcfb"
          }
        ],
        "isHidden": true,
        "lineageTag": "1b55c1c1-5af4-421c-9e84-d4b14cc0b046",
        "partitions": [
          {
            "name": "LocalDateTable_af4f99d0-a7e4-4bf4-a3ca-4429e1d7f0c2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_Report'[DEPARTUREDATE])), 1, 1), Date(Year(MAX('KFR_ET_Report'[DEPARTUREDATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e2060e6c-ad33-450c-aaf3-64a78030d959",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f6abb141-55af-4f02-a5d2-ed904418d6df",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a3a9b568-8f5e-4725-bfd0-b03c354d38e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ee3a0a2f-4f96-4622-af47-f4002a097b6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "630a2329-793d-41b5-9e09-c89fd9b0d1d1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "43dbc6c0-08b6-4d4c-b28e-c07334095b45",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "44d62c50-e1a1-4837-914f-c80486ff1797",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3ae39e62-5bd7-49f5-becb-60870da55f44",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "75d3521b-5266-4957-b140-bcffa6c35a0e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "25f8359c-3c19-4d84-b815-ec2b34945ad3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "476b0fc0-0496-4ba4-b08c-ef39ede2e988",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1a8a3cf3-f788-4abe-a9d3-ad73713cff17",
                "ordinal": 3
              }
            ],
            "lineageTag": "75de11e0-676b-4d51-8515-dfd68dca2b11"
          }
        ],
        "isHidden": true,
        "lineageTag": "e34c9f8f-5816-42ba-ae31-49b65c87fd28",
        "partitions": [
          {
            "name": "LocalDateTable_e2060e6c-ad33-450c-aaf3-64a78030d959",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_Report'[Date])), 1, 1), Date(Year(MAX('KFR_ET_Report'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "RegionCompTable",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3c47dee-8bae-4156-bb41-d6e5debb2dab",
            "sourceColumn": "TourRegionCode",
            "summarizeBy": "none"
          },
          {
            "name": "COMPTYPECODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "370aed34-b3ad-483b-b3f0-bf4ccefbd01d",
            "sourceColumn": "COMPTYPECODE",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONCOMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc7f25ef-4bd1-4426-a472-4b67d1807241",
            "sourceColumn": "REGIONCOMP",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONCOMP_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff7dae7c-de5f-4169-a332-5cdb80e851e9",
            "sourceColumn": "REGIONCOMP_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a1573b5e-ec93-4f3d-8da2-fab5801a3d37",
        "partitions": [
          {
            "name": "RegionCompTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_REGIONCOMPTABLE_V\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"TOURREGIONCODE\", \"TourRegionCode\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CurrencyTable",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CURRENCYCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "873f5637-0342-4e56-9985-04ccb7d205e0",
            "sourceColumn": "CURRENCYCODE",
            "summarizeBy": "none"
          },
          {
            "name": "CURRENCY_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cfea950b-83cb-4b83-825a-32362d0cdb85",
            "sourceColumn": "CURRENCY_INDEX",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ff988a0-a083-43e3-a091-5215a3da9e45",
        "partitions": [
          {
            "name": "CurrencyTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_CURRENCYTABLE_V\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KFR_ET_DIM_Slicer2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e46326d-1359-4476-ac61-09892fc1b414",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d022443-3c37-4e2b-8549-bddaf755fe2f",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ba2a9a6e-81ba-4409-8de6-2dcda6adf988"
                },
                "isDefault": true,
                "relationship": "a6ac73da-a6b8-4628-a50e-7464ec54b39f"
              }
            ]
          },
          {
            "name": "MY_KFR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cbb5ff9f-136f-4b64-bf6d-f9069353060b",
            "sourceColumn": "MY_KFR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "19c6e4f4-6ffc-4d1c-a92a-6f1d4e087aff",
            "sourceColumn": "TP_year",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e43c99b0-2ed3-47f8-b31f-029a36466d1f",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "MY_PERIODS_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3509b8d0-9e18-47a9-aff7-a94af9ba72ff",
            "sourceColumn": "MY_PERIODS_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "FX_period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe65bad9-0ad7-4b2d-b539-91d1e81715f1",
            "sourceColumn": "FX_period",
            "summarizeBy": "none"
          },
          {
            "name": "MY_FX_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73b8cbb5-22d5-44a7-abee-61d481924b40",
            "sourceColumn": "MY_FX_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c237a3a5-0b04-4f28-9b50-11975fa6cdd3",
        "measures": [
          {
            "name": "Slicer_FX_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer2[My_FX_Index])",
            "lineageTag": "71454444-fc90-4b05-836e-6fa8ad2fb293"
          },
          {
            "name": "Slicer_KFR_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer2[My_KFR_Index])",
            "lineageTag": "150e537a-c692-43c6-bee9-66788bd7b48f"
          },
          {
            "name": "Slicer_Periods_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer2[My_Periods_Index])",
            "lineageTag": "460ba630-91cb-4970-b471-9f7d473644d8"
          }
        ],
        "partitions": [
          {
            "name": "KFR_ET_DIM_Slicer2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_DIM_SLICER#(lf)WHERE UPPER(TP_Desc) NOT LIKE '%_PY'\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"TP_DESC\", \"TP_Desc\"}, {\"DATE\", \"Date\"}, {\"TP_YEAR\", \"TP_year\"}, {\"PERIOD\", \"Period\"}, {\"FX_PERIOD\", \"FX_period\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ba2a9a6e-81ba-4409-8de6-2dcda6adf988",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cb1efa2d-8002-4d89-8b54-748a46d9fafb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e003eb8a-e157-4e9e-a919-2286838c6b57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "75953095-4c46-4d61-bf52-bdd2ea592a8b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "65beba5f-1f17-4411-bc9a-be5aadbfa82d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5e58f03d-1915-42bf-a144-1caa394d89f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "455021fe-22b2-450e-9965-e958ebcde5ab",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "cbabc017-9a65-4c69-8470-174095e15317",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d3e4d867-1a2d-49a6-b15c-1e552bd92cdf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "261afcaa-9485-4fe7-9c34-c5e6eb9bc3d5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "11472912-3913-4bb2-a5e0-09049e85f55a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4eaab715-0353-4227-b5e1-291b3c4084bb",
                "ordinal": 3
              }
            ],
            "lineageTag": "01ed210a-ca81-457d-8346-923586a2a4fb"
          }
        ],
        "isHidden": true,
        "lineageTag": "0e59c47e-2326-4e0c-8883-f58ad72da0aa",
        "partitions": [
          {
            "name": "LocalDateTable_ba2a9a6e-81ba-4409-8de6-2dcda6adf988",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_DIM_Slicer2'[Date])), 1, 1), Date(Year(MAX('KFR_ET_DIM_Slicer2'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "KFR_ET_DIM_Slicer1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82cb0080-c6a7-4493-9adf-7f2edf3e7528",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9487680e-4e30-4d2c-bf26-74e2111fdac5",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_86061e0a-7362-49b8-bd90-4e103c4ea353"
                },
                "isDefault": true,
                "relationship": "14b5c9bb-dc73-4921-80b2-e9a7a132286c"
              }
            ]
          },
          {
            "name": "MY_KFR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a73d7c88-0db0-4fe4-aa7d-ac107fde2861",
            "sourceColumn": "MY_KFR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "81976738-0de0-4811-bfa5-c522aa9d031d",
            "sourceColumn": "TP_year",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2723cbda-0ce5-4fe5-bf5d-89235152e1a7",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "MY_PERIODS_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c69ab82d-92b6-4a05-add9-b917f199425a",
            "sourceColumn": "MY_PERIODS_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "FX_period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bf36b25-d5a4-4664-acd1-2a7331e467fc",
            "sourceColumn": "FX_period",
            "summarizeBy": "none"
          },
          {
            "name": "MY_FX_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12e6c76d-e347-4c1c-bed2-252e91b2f4c4",
            "sourceColumn": "MY_FX_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f00e0c31-e0d0-448d-85d8-d79d79e43828",
        "measures": [
          {
            "name": "Slicer_KFR_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer1[My_KFR_Index])",
            "lineageTag": "34be72f4-4b64-43a2-8764-aa623ee65a04"
          },
          {
            "name": "Slicer_FX_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer1[My_FX_Index])",
            "lineageTag": "1e379761-0833-4187-b2c7-f010963e1142"
          },
          {
            "name": "Slicer_Periods_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE(KFR_ET_DIM_Slicer1[My_Periods_Index])",
            "lineageTag": "75e154a6-e89d-470c-a81c-5fd77a8abf81"
          }
        ],
        "partitions": [
          {
            "name": "KFR_ET_DIM_Slicer1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_DIM_SLICER#(lf)WHERE UPPER(TP_Desc) NOT LIKE '%_PY'\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"TP_DESC\", \"TP_Desc\"}, {\"DATE\", \"Date\"}, {\"TP_YEAR\", \"TP_year\"}, {\"PERIOD\", \"Period\"}, {\"FX_PERIOD\", \"FX_period\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_86061e0a-7362-49b8-bd90-4e103c4ea353",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "610d4409-970f-4743-9eb3-f16944404951",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "065c9dbb-e0de-4587-9067-42c70c0b2bfe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5c7eae80-369d-4c69-9b49-f0d345bafd51",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b3662429-a6c6-4d89-9668-aaba10f4978d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "13429327-0504-4219-8adb-ea2654fccc80",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "614c7302-d68b-4b25-bade-d37aa557b21b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70c1ad37-3242-4857-b2eb-a4b24e821027",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5f348495-4f06-4b31-9358-ec8f59d9b8a8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c0dbce4d-3b9f-4d91-9587-3888eb434ba3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1770d74d-5168-4972-aede-a245cc2d5010",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "020a1bf4-e176-436a-adbb-fd585750cf40",
                "ordinal": 3
              }
            ],
            "lineageTag": "ffd0989d-4399-49ab-a50b-58ac1e2711e6"
          }
        ],
        "isHidden": true,
        "lineageTag": "7be5e11f-d898-460c-9f12-f3759336e6a8",
        "partitions": [
          {
            "name": "LocalDateTable_86061e0a-7362-49b8-bd90-4e103c4ea353",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_DIM_Slicer1'[Date])), 1, 1), Date(Year(MAX('KFR_ET_DIM_Slicer1'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "KFR_ET_TravelPattern_Unmatched",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "237dc88a-2361-4fc5-ae32-e5859cb4a264",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "KFR_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d279d6e-21c2-474b-b24f-ebb9cd7ca7ca",
            "sourceColumn": "KFR_DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b3ab996e-41d5-4c37-bbe6-9d01d770e1cd"
                },
                "isDefault": true,
                "relationship": "0ebff29c-c0f9-4c66-99ef-d52c2f12f269"
              }
            ]
          },
          {
            "name": "ProductMarketCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f35c89c6-74c3-4920-bede-891e16ac624d",
            "sourceColumn": "ProductMarketCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourTypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fffc2d4e-5f41-43a6-b293-7deeb06144c8",
            "sourceColumn": "TourTypeCode",
            "summarizeBy": "none"
          },
          {
            "name": "BUSINESSUNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "979505d0-a91f-43b9-9138-d7c8e9c61d8d",
            "sourceColumn": "BUSINESSUNIT",
            "summarizeBy": "none"
          },
          {
            "name": "FYCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef6f5bc2-0ba3-462e-b09f-eb947c9de71a",
            "sourceColumn": "FYCODE",
            "summarizeBy": "none"
          },
          {
            "name": "FY_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "2f333a30-35e6-492e-aa61-777ac59e302a",
            "sourceColumn": "FY_year",
            "summarizeBy": "sum"
          },
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b991a8d-9965-419d-b3a7-ff018ac34c27",
            "sourceColumn": "TourRegionCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d915c526-4b54-47a4-b820-2eae58afc992",
            "sourceColumn": "TourCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourVersionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "74a3407e-f9f5-45c2-ba06-9d66e266f2fd",
            "sourceColumn": "TourVersionCode",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURSTARTLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39a51d1e-417e-4b65-8741-fa136cf2adbe",
            "sourceColumn": "TOURSTARTLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "TOURENDLOCATIONCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36fb80b3-21aa-482f-ae93-9babb71f7dbb",
            "sourceColumn": "TOURENDLOCATIONCODE",
            "summarizeBy": "none"
          },
          {
            "name": "SALESTOURID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d59bff12-46b8-4fae-9557-08afdc96e953",
            "sourceColumn": "SALESTOURID",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTUREDATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9d88086f-2529-4423-844e-2218e33ca74e",
            "sourceColumn": "DEPARTUREDATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b54472eb-b572-4a2f-b7fc-28bc7c405a12"
                },
                "isDefault": true,
                "relationship": "60cc361e-df77-47ee-9a91-1526ea173cf5"
              }
            ]
          },
          {
            "name": "TRAVELLERS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15446cbd-1e5b-4997-9e57-10cb0debc1c2",
            "sourceColumn": "TRAVELLERS",
            "summarizeBy": "sum"
          },
          {
            "name": "PAYINGPAX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6e15c89-9f97-430e-9b98-1f477b51f6ee",
            "sourceColumn": "PAYINGPAX",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "14568817-9dcc-4de5-a7fd-f82a3ff25f7e",
            "sourceColumn": "BUSCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BUSEXTCOUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "80b2a991-4864-4f39-821e-3b2187fc606b",
            "sourceColumn": "BUSEXTCOUNT",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetSeasonNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5070f47-8847-492a-8357-368ee47c5d48",
            "sourceColumn": "BudgetSeasonNum",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_KEY_GUESS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed1c09cb-0591-44fb-9bdb-68fede863e3d",
            "sourceColumn": "TP_KEY_GUESS",
            "summarizeBy": "none"
          },
          {
            "name": "TP_key_ext",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90023138-3692-4614-8676-8ff8e8226756",
            "sourceColumn": "TP_key_ext",
            "summarizeBy": "none"
          },
          {
            "name": "TP_KEY_EXT_UNIQUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "936163c4-c9c4-4e88-b337-305ac9f1540c",
            "sourceColumn": "TP_KEY_EXT_UNIQUE",
            "summarizeBy": "none"
          },
          {
            "name": "ADJYEAR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f32d2d9e-1f31-498a-8e8d-95c17bbab660",
            "sourceColumn": "ADJYEAR",
            "summarizeBy": "sum"
          },
          {
            "name": "ADJVERSION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3adf7a8e-b349-400c-8295-3b0e2cce27fd",
            "sourceColumn": "ADJVERSION",
            "summarizeBy": "sum"
          },
          {
            "name": "PERFECT_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d9cf6b20-8928-4f1a-8b50-4dd39da02a84",
            "sourceColumn": "PERFECT_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "NEW_REGION_TEXT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cbf1bf6-63bd-4b38-84b1-25fdecc34d79",
            "sourceColumn": "NEW_REGION_TEXT",
            "summarizeBy": "none"
          },
          {
            "name": "NEW_TOURCODE_TEXT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "188a3cc4-dcfa-47ef-8da3-c4b1863918ef",
            "sourceColumn": "NEW_TOURCODE_TEXT",
            "summarizeBy": "none"
          },
          {
            "name": "NEW_YEAR_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d4b375d-3685-4232-a7db-1ce26bd32188",
            "sourceColumn": "NEW_YEAR_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "NEW_VERSIONCODE_NUMBER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "641d0227-0327-4efe-9021-a19d3b3f11b2",
            "sourceColumn": "NEW_VERSIONCODE_NUMBER",
            "summarizeBy": "sum"
          },
          {
            "name": "TOURDURATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0660f5a1-fe21-4bef-af71-195f3a051e21",
            "sourceColumn": "TOURDURATION",
            "summarizeBy": "sum"
          },
          {
            "name": "TP_key_adj",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c5bb9ad-8b65-46ed-8918-5dc918e7528a",
            "sourceColumn": "TP_key_adj",
            "summarizeBy": "none"
          },
          {
            "name": "MY_KFR_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8dd40301-2b27-4a90-ae2f-97feb1f1eac8",
            "sourceColumn": "MY_KFR_INDEX",
            "summarizeBy": "sum"
          },
          {
            "name": "MY_FILTER_KEY_INDEX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e8de805-e4c8-4398-85e6-6b5365db47d8",
            "sourceColumn": "MY_FILTER_KEY_INDEX",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e05d35c6-387c-4cf2-95e8-fb07eebf0c8f",
        "measures": [
          {
            "name": "Unmatched_My_Travellers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(KFR_ET_TravelPattern_Unmatched[Travellers])",
            "lineageTag": "a8e0c46d-04b7-46cc-b667-97a6408212d6"
          },
          {
            "name": "Unmatched_explanation",
            "expression": [
              "",
              "",
              "Var Calc = ",
              "    SWITCH(TRUE()",
              "        , SELECTEDVALUE(KFR_ET_TravelPattern_Unmatched[TP_key_adj]) = BLANK(), \"Missing Active TourCode in Atlas\"",
              "        , \"No Required Budget items in TourSpec\"",
              "    )",
              "",
              "Return Calc  "
            ],
            "lineageTag": "f40b677a-2fed-43a4-b91d-f14efc1e9964"
          }
        ],
        "partitions": [
          {
            "name": "KFR_ET_TravelPattern_Unmatched",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_TRAVELPATTERN_UNMATCHED_V\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"TP_DESC\", \"TP_Desc\"}, {\"PRODUCTMARKETCODE\", \"ProductMarketCode\"}, {\"TOURREGIONCODE\", \"TourRegionCode\"}, {\"TOURTYPECODE\", \"TourTypeCode\"}, {\"TOURCODE\", \"TourCode\"}, {\"TOURVERSIONCODE\", \"TourVersionCode\"}, {\"BUDGETSEASONNUM\", \"BudgetSeasonNum\"}, {\"TP_KEY_EXT\", \"TP_key_ext\"}, {\"TP_KEY_ADJ\", \"TP_key_adj\"}, {\"FY_YEAR\", \"FY_year\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b3ab996e-41d5-4c37-bbe6-9d01d770e1cd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7374decf-1f5b-4909-a22c-e006cedbbd99",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "bc30fe81-3329-4564-ae1e-6da26c2e10f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "288311b0-a191-4d56-b51f-57f218712651",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1a7f6fb3-9caf-45ce-b92b-719055ab8107",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "583be1fb-8023-4bdd-9d5b-0c72521db471",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "60d42aec-6be0-4dc1-a9cd-b427c135df3c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9d5a0e04-ebb2-4487-9452-b8fed5cb8106",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f3a60438-d636-447c-aa7d-0c10b304400a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2ce7dc80-83b7-4e27-8607-f21ad64dd166",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5e1cc388-a22b-4d6e-9dbc-cf2298e27d6f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1110905d-073d-4ffe-95c0-23b24d96155f",
                "ordinal": 3
              }
            ],
            "lineageTag": "86c0930f-95e6-465a-8dfc-b38ff2722e9c"
          }
        ],
        "isHidden": true,
        "lineageTag": "311cc2f4-485e-4098-aa60-3b719b319669",
        "partitions": [
          {
            "name": "LocalDateTable_b3ab996e-41d5-4c37-bbe6-9d01d770e1cd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_TravelPattern_Unmatched'[KFR_DATE])), 1, 1), Date(Year(MAX('KFR_ET_TravelPattern_Unmatched'[KFR_DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b54472eb-b572-4a2f-b7fc-28bc7c405a12",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2f8ea46d-a46f-4542-986f-af48b2b806c6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d8e47d82-a171-4ff9-a591-b16dbb85289c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "49f2cb5a-c8fa-49dc-8cfa-ba1d8be0423e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9b8335bf-fa32-4300-9e36-6557a29476e6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "fc2e9218-a595-4329-9f06-2b78a70af12b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "499a2f1f-81e0-4bb0-8f59-0767079f75ce",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b744e89a-92af-48bf-8442-fe5b405d4534",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6cde4eed-4b4b-485e-b95d-c1f8b5803f48",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "888a9538-8b57-4668-ad5f-06cd42bf7711",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9aa25d2f-3605-4e6d-9430-c19b8c5ecc3f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "22708460-16ac-4184-ab48-7f350b5b3432",
                "ordinal": 3
              }
            ],
            "lineageTag": "5cecae75-136b-4f8b-a470-7d732e4f73d2"
          }
        ],
        "isHidden": true,
        "lineageTag": "958cb324-1f8b-46b8-86e8-e6994f582820",
        "partitions": [
          {
            "name": "LocalDateTable_b54472eb-b572-4a2f-b7fc-28bc7c405a12",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('KFR_ET_TravelPattern_Unmatched'[DEPARTUREDATE])), 1, 1), Date(Year(MAX('KFR_ET_TravelPattern_Unmatched'[DEPARTUREDATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "KFR_ET_TravelPattern_Unmapped",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TP_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ade6e064-95f9-4643-99fb-1d48997fb5f7",
            "sourceColumn": "TP_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "FY_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f9093741-4717-4df1-b1a7-70b4c40fb25c",
            "sourceColumn": "FY_year",
            "summarizeBy": "sum"
          },
          {
            "name": "TourRegionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4a55ee9-08af-4c65-8034-ce7ee7afa0d4",
            "sourceColumn": "TourRegionCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fec0096-d895-4af5-acf0-40596c029782",
            "sourceColumn": "TourCode",
            "summarizeBy": "none"
          },
          {
            "name": "TourVersionCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93a6387e-4fe7-4ca6-9d5a-f474ce7cd85e",
            "sourceColumn": "TourVersionCode",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "950c76db-2304-4dfe-8a3d-811518b82c83",
        "partitions": [
          {
            "name": "KFR_ET_TravelPattern_Unmapped",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"eftours_us.us-east-1.snowflakecomputing.com\",\"DEV_REPORTING_WH\",[Role=\"DEV_REPORTER\"]){[Name=\"DEV_ANALYTICS\"]}[Data], \"SELECT *#(lf)FROM DEV_ANALYTICS.REPORTING_LANDOPS.KFR_ET_TRAVELPATTERN_UNMAPPED_V\", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"TP_DESC\", \"TP_Desc\"}, {\"TOURREGIONCODE\", \"TourRegionCode\"}, {\"TOURCODE\", \"TourCode\"}, {\"TOURVERSIONCODE\", \"TourVersionCode\"}, {\"FY_YEAR\", \"FY_year\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}